### ISSUE TITLE
uma plugin not listed

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#10]
![image](https://user-images.githubusercontent.com/3717101/34273082-860fd940-e658-11e7-86a7-01da8c93eed2.png)

Are there any other plugins that are also missing?

**Comment by ldeveloperl1985** [comment]
@nynymike  This window only shows added plugins. If you want other plugins then click on `+ ADD GLOBAL PLUGINS` button.
Doc description: https://github.com/GluuFederation/gluu-gateway#5-plugins

**Comment by nynymike** [comment]
ok, I can see it now.
