### ISSUE TITLE
Bug: extra scroll in SETTINGS

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#100]
Please refer to the video. When you go to Notifications --> Applications and move the mouse over the Slack logo, another scroll bar appears on the right. It's not a bloker, but it would improve UX.
![2018-05-08_13h05_17](https://user-images.githubusercontent.com/38302725/39742717-e04f36d0-52e1-11e8-9a40-075a858eb166.gif)

**Comment by ldeveloperl1985** [comment]
I tested with 

1. Ubuntu 14.04 trusty + Firefox 59.0.3  
2. Windows 10 + Firefox 59.0.3 

But not able to reproduce in both environment.
Review video https://youtu.be/fwwZ0yGBA1k.
I think we can close it for now. 
What do you think Natalia?

**Comment by natt-tester** [comment]
Ok, it's not a bloker and I think it can wait until we get more reproduction steps.
