### ISSUE TITLE
Unify the DELETE button strings

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#101]
Please make sure that all strings for the DELETE buttons have the same strings. Now the majority has "Really want to delete the selected item?", but there's also "Are you sure you want to delete this snapshot?" for the Snapshot DELETE button. It's a bit inconvenient UX-wise; I'd suggest sticking to one version, maybe "Do you want to delete the selected item?"  with YES and CANCEL.

![2018-05-08_12h36_33](https://user-images.githubusercontent.com/38302725/39743243-a99c2d58-52e3-11e8-98cc-d2d223b1e111.png)
![2018-05-08_12h37_37](https://user-images.githubusercontent.com/38302725/39743250-aec4ca60-52e3-11e8-97ce-66159b696346.png)

**Comment by natt-tester** [comment]
The strings are unified, but now after being clicked, the buttons become white until you click on something else. Please take a look:

**Comment by ldeveloperl1985** [comment]
Done
