### ISSUE TITLE
Display GG version

### ISSUE THREAD

**Issue by kepuss** [GluuFederation/gluu-gateway#106]
GG should display version somewhere in GUI. My proposition is left bottom part of left panel (but can be somewhere else). 
Version value should be taken from config file which can be easily replaced. 
The file will be replaced during jenkins package build.

**Comment by ldeveloperl1985** [comment]
Done. You just need to set value in GG setup script.py
https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3/setup/setup-gluu-gateway.py#L91

**Comment by natt-tester** [comment]
Agreed, it's done:
![2018-05-12_19h30_04](https://user-images.githubusercontent.com/38302725/39955944-fef90804-561a-11e8-9068-840fcfd278c6.png)
