### ISSUE TITLE
Enhancement: unify toggle bar descriptions

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#108]
Please refer to the green example and change the other strings accordingly for better UX. The enhancement involves all AP dialog windows.

![2018-05-11_13h57_51](https://user-images.githubusercontent.com/38302725/39906072-df7e7420-5523-11e8-86c7-fb1d73977206.png)

**Comment by ldeveloperl1985** [comment]
Done
![unifytoggle](https://user-images.githubusercontent.com/2329776/39913699-7717c9e8-5520-11e8-8fc6-07fb062fbba1.png)

**Comment by natt-tester** [comment]
Looks great! But I think we should apply it everywhere to make it consistent, so please change it to YES nad No also here: 

![2018-05-12_21h38_14](https://user-images.githubusercontent.com/38302725/39956938-b1a79de6-562d-11e8-8f1f-72e884dc1b6e.png)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, it's done :)
