### ISSUE TITLE
Wrong place to move configuration files

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-gateway#111]
I think instead of running next commands from `postinst` during install we need to put files in right place before hand in GG package.
```
mv /etc/init.d/kong.init.d /etc/init.d/kong
mv /etc/init.d/konga.init.d /etc/init.d/konga
```

Also current approach not removes config files at uninstall

**Comment by nikdavnik** [comment]
In this case we are not moving files but just changing names. 
To solve removal issue I build new package with postrm script to remove /etc/init.d/kong and /etc/init.d/konga files during uninstall.

https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-gateway_3.1.3-10~trusty+Ub14.04_amd64.deb

**Comment by natt-tester** [comment]
Hi! I would like to test this issue, but I want to double check if I understand it correctly: we want to remove  /etc/init.d/kong and /etc/init.d/konga files with uninstall because now the config files are not removed. Is it correct? Thanks!

**Comment by nikdavnik** [comment]
I renamed init files in github, so following lines have been removed as we do not need them anymore.
mv /etc/init.d/kong.init.d /etc/init.d/kong
mv /etc/init.d/konga.init.d /etc/init.d/konga

Closing the issue. thanks

**Comment by natt-tester** [comment]
Agreed: I've tested it and confirm that the files are removed.
