### ISSUE TITLE
Enhancement: change the location of the + in plugins

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#114]
Please refer to the screenshots -- in some cases, the + sign isn't aligned with the tick sign, and in some -- it's not even visible when the plugin is active. UX-wise, I think the best idea would be to place them at the same height if you're always able to edit the settings (the proposed solution in the 3rd screenshot).
![2018-05-12_20h36_04](https://user-images.githubusercontent.com/38302725/39956529-ed19e814-5625-11e8-98f4-d866076ac4de.png)
![2018-05-12_20h37_33](https://user-images.githubusercontent.com/38302725/39956531-f717f52c-5625-11e8-81ea-9b4d6c1f7a00.png)
![2018-05-12_20h36_04](https://user-images.githubusercontent.com/38302725/39956619-96717534-5627-11e8-93d3-5044823a9860.png)

**Comment by natt-tester** [comment]
Found a few renegades here:
![2018-05-18_20h12_01](https://user-images.githubusercontent.com/38302725/40229634-290d7122-5ad8-11e8-9ba4-dcf23923c987.png)

**Comment by ldeveloperl1985** [comment]
Done
![screenshot 1](https://user-images.githubusercontent.com/2329776/40230583-a9a215ae-5ab5-11e8-9579-fe5f9a2be184.png)
