### ISSUE TITLE
Bug (?): unnecessary paginator

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#115]
Please refer to the GIF and screenshot -- I think the paginator is unnecessary when there are no plugins or when they can be displayed on one page.
![2018-05-12_21h13_23](https://user-images.githubusercontent.com/38302725/39956752-fe73225c-5629-11e8-9436-0669c6fb808f.png)
![2018-05-12_21h12_31](https://user-images.githubusercontent.com/38302725/39956755-02d809fc-562a-11e8-8231-19dd5570f5d9.gif)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, it's fixed.
