### ISSUE TITLE
Accept GLUU-LICENSE should be first

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#12]
A person must accept the GLUU-SUPPORT license before answering the setup wizard questions.

**Comment by ldeveloperl1985** [comment]
Solved https://github.com/GluuFederation/gluu-gateway/blob/master/setup/setup-gluu-gateway.py#L462

**Comment by ldeveloperl1985** [comment]
Solved, Tested in latest build gluu-gateway 0.1.37
