### ISSUE TITLE
Add Instrumentation Support to Tracing Trace Requests / Responses

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#123]
It would be great to trace a transaction through the request, oxd api calls, and response. We can use OpenTracing: 
http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks

**Comment by ldeveloperl1985** [comment]
We don't need to do anything for this. Kong provides default tracing plugin `zipkin` for this.
