### ISSUE TITLE
Enhancement: change + in active plugin windows to EDIT

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#125]
Please change the marked + icon to the EDIT icon in all views (and add it to CONSUMER section plugins) to improve UX.
Please make sure that it's used in all views, buttons and dialog windows dealing with edition.
![2018-05-21_19h02_30](https://user-images.githubusercontent.com/38302725/40299431-93f131b0-5d29-11e8-88d4-b9c4dbe725b5.png)

**Comment by ldeveloperl1985** [comment]
I've removed extra `+` icon and user can edit plugin from plugin, service and route plugin list view.
