### ISSUE TITLE
Enhancement: change X icon to DELETE/bin icon 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#127]
Please change the marked X icon to the DELETE/bin icon in all views to improve UX.
Please make sure that it's used in all views, buttons and dialog windows dealing with deletion.

![2018-05-22_13h42_04](https://user-images.githubusercontent.com/38302725/40341125-a82acd10-5dc6-11e8-9384-7515d0e4dcdb.png)

**Comment by ldeveloperl1985** [comment]
Done
![cc](https://user-images.githubusercontent.com/2329776/48395941-d1e16b80-e73e-11e8-8aa4-49d307b374dd.png)
