### ISSUE TITLE
konga should listen only on localhost 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#13]
```
# netstat -antlp | grep 1338
tcp6       0      0 :::1338                 :::*                    LISTEN      16187/node

```

This should be `127.0.0.0:1338`

**Comment by nynymike** [comment]
Can you confirm this in the latest package and close the issue?

**Comment by ldeveloperl1985** [comment]
@nynymike   Solved, Tested in new build
![image](https://image.prntscr.com/image/prOtV2_CQiGan3GEG5OA0Q.png)
