### ISSUE TITLE
Bug: Unable to install GG in Ubuntu 16.04

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#131]
Please take a look at the logs and screenshots: the installation fails every time I try it and needs proper debugging.

![2018-05-28_19h49_49](https://user-images.githubusercontent.com/38302725/40612056-530f4c52-62bc-11e8-81e0-ae30c9755743.png)
![2018-05-28_21h10_15](https://user-images.githubusercontent.com/38302725/40612059-57922614-62bc-11e8-8f37-105ea86977d4.png)

[gluu-gateway-setup.log](https://github.com/GluuFederation/gluu-gateway/files/2044819/gluu-gateway-setup.log)
[gluu-gateway-setup_error.log](https://github.com/GluuFederation/gluu-gateway/files/2044820/gluu-gateway-setup_error.log)

**Comment by nikdavnik** [comment]
please check new build
https://repo.gluu.org/ubuntu/pool/main/xenial-devel/gluu-gateway_3.1.3-15~xenial+Ub16.04_amd64.deb

**Comment by natt-tester** [comment]
It's done, I've successfully installed GG in Ubuntu 16.04 with no errors.
