### ISSUE TITLE
Enhancement: remove error warning upon successful edition

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#132]
Please refer to the GIF and remove the error warning upon successful edition of and Upstream target. There shouldn't be an error visible after the green success pop-up. When you reload the view, the error disappears.

![2018-05-29_12h55_50](https://user-images.githubusercontent.com/38302725/40635976-262dbb40-6340-11e8-8807-cccbb87c64a4.gif)

**Comment by ldeveloperl1985** [comment]
This is old kong module. we have updated with latest kong. Done with issue https://github.com/GluuFederation/gluu-gateway/issues/229
