### ISSUE TITLE
Enhancement (?): show global Plugins as switched off

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#133]
Please refer to the GIF and advise: shouldn't the switched off global Plugins be shown as inactive/gray in the Dashboard section? I think it would be less confusing for the user :)

![2018-05-29_13h07_10](https://user-images.githubusercontent.com/38302725/40636293-be7836ea-6341-11e8-8077-facc92627875.gif)

**Comment by ldeveloperl1985** [comment]
It is ok because it highlighted `enabled_in_cluster` plugins, response from Kong API.
![acl](https://user-images.githubusercontent.com/2329776/46408752-cc9d0400-c730-11e8-95fb-04aa09c0babd.png)
