### ISSUE TITLE
Enhancement: add a table with all API/Consumer ids

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#137]
It would be great to have a table with all API/Consumer details: client_ids and oxd_ids in the DASHBOARD section to drastically improve the UX.

![2018-06-05_10h49_41](https://user-images.githubusercontent.com/38302725/40949025-36048f7a-68af-11e8-85f1-8e47c6aa6f0f.png)

**Comment by ldeveloperl1985** [comment]
We already designed pages to show client id and oxd id so we do not need to show on the dashboard.
Related to issue https://github.com/GluuFederation/gluu-gateway/issues/136

**Comment by ldeveloperl1985** [comment]
Done. @natt-tester please take update from branch 3.1.4 and check
![paginationondash](https://user-images.githubusercontent.com/2329776/41910077-449dcde0-7966-11e8-99ab-0db8e869c7d9.png)

**Comment by natt-tester** [comment]
@ldeveloperl1985, I've tested it with 3.1.4 and see 3 areas to discuss:

1. I know that the task says all API/Consumer ids, but I think we need all ids to make the user understand how many applications they have already created. As it is now, the apps created when you install the GG and log in are not shown, and that can be misleading.

2. I see that get-client-token calls for Consumers are presented with their names, which is good and convenient to use. But what if the user changed the name? Shouldn't the table be responsive to such changes? For now, the name stays the same, so after a while it may become hard to track.

3. I can't see any apps created in my new vm in the ecom platform. Is it because of the recent changes with server_name? It worked fine with the last 3.1.3 version.

**Comment by ldeveloperl1985** [comment]
1. How to track actively created apps? 
    @natt-tester, @pharingee Is any API to fetch actively create Apps from oxd e-comm and to show in GG?
    @yuriyz is there any way to track active client or Apps from oxd?
2. I've checked, After update consumer with name, also update the dashboard table
3. @yuriyz, @pharingee can you please take a look why this happens. We only update the server name. or @natt-tester you need to double check it.

**Comment by natt-tester** [comment]
1. Sorry, I don't really get the question :)
2. @ldeveloperl1985 -- I see that it's not the Consumer name, but the Consumer credential name that gets updated:
![2018-06-28_19h04_38](https://user-images.githubusercontent.com/38302725/42025389-cecc7974-7b07-11e8-8c80-0df1f91bf326.gif)
But it's fine, as long as we add a description in the docs. From the UX point of view, I think we also need to consider the aspect of all created/all existing credentials because if you create and delete UMA APIs, make get-client-token calls and then delete the Consumers, you end up with two different tables in GG and ecom platform:
![2018-06-28_19h25_59](https://user-images.githubusercontent.com/38302725/42026085-9219d8bc-7b09-11e8-9baa-b3e24652648b.png)
![2018-06-28_19h26_12](https://user-images.githubusercontent.com/38302725/42026089-93ee9ec0-7b09-11e8-91f0-27e1cc1d3a41.png)

3. @yuriyz, @ldeveloperl1985, false alarm -- I'd entered different credentials by mistake, the third issue is no longer valid.

**Comment by yuriyz** [comment]
@natt-tester glad to hear re: false alarm
@ldeveloperl1985 oxd reports active clients to License Server, then you can see it via License Server API by given `licenseId`, example: https://license.gluu.org/oxLicense/rest/statistic/client/monthly?licenseId=b9d9140e-0732-4a96-b4be-215597377a10

**Comment by ldeveloperl1985** [comment]
@yuriyz, I am getting cross-origin problem. can you allow cross-origin access on license.gluu.org?
![cross](https://user-images.githubusercontent.com/2329776/42082584-063641e4-7ba6-11e8-974d-ba376e4c7ec7.png)

**Comment by yuriyz** [comment]
@ldeveloperl1985 Added "Access-Control-Allow-Origin", "*" for GET requests. Please check.

**Comment by yuriyz** [comment]
![image](https://user-images.githubusercontent.com/2013070/42088813-9016e20e-7ba3-11e8-8921-49b897fb6336.png)

**Comment by ldeveloperl1985** [comment]
Thanks, Now getting successful with data. Problem is in my side that is in AngularJS HTTP request.

**Comment by ldeveloperl1985** [comment]
@natt-tester I've fetch active client from oxd-license server and show on GG dashboard. Please check.
![clients_info](https://user-images.githubusercontent.com/2329776/42157194-ae47ba46-7e0a-11e8-8b6c-49e8a04ffe78.png)

**Comment by ldeveloperl1985** [comment]
As we removed license from oxd so we don't need this now
