### ISSUE TITLE
Bug: unstable oxd-server on VM, vague error message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#138]
Preconditions: GG installed on the same virtual machine together with oxd, both running
Tested on Ubuntu 16.04 and 14.04

Steps:

    Log in to the GG Admin Portal
    Switch off the virtual machine
    Wait several hours
    Switch it back on
    Try to log in to the Admin Portal again

Expected: The user is able to log in OR the user is unable to log in, but there's a meaningful error text displayed
Actual: There's only info about an internal server error (see the screenshot).

![2018-06-04_20h23_37](https://user-images.githubusercontent.com/38302725/41028520-f6eee704-69bc-11e8-9fdb-d310bf6a4b6b.png)

When I leave the machine running for several hours and the GG session expires, it's possible to get also another error. It might be caused by a slow Internet connection, but for better UX I recommend something more user-friendly.

![2018-06-05_16h13_43](https://user-images.githubusercontent.com/38302725/41028598-228fe020-69bd-11e8-95d7-48ba1e7449c2.png)

[oxd-server(2).log](https://github.com/GluuFederation/gluu-gateway/files/2075459/oxd-server.2.log)

I have consulted it with Yuriy, who writes: "It seems that VM on which you run oxd-server lost internet connection and as result oxd-server was not able to operate in normal mode. Logs are full of errors like:

2018-06-04 11:17:24,195 ERROR [org.xdi.oxd.server.service.DiscoveryService] Unable to fetch discovery information for op_host: https://ce-dev6.gluu.org

And

Caused by: java.net.UnknownHostException: license.gluu.org

About error message, please open ticket to improve it on GG. Hopefully GG can identify when internet goes down. oxd-server returns internal error because if it gets exception like java.net.UnknownHostException or NullPointerException from technical point of view it can not report that internet is down because it may be mis-configuration."

**Comment by ldeveloperl1985** [comment]
I am closing it. because you hosted application locally in VM so GG is able to calling OXD. No any way to detect internet is active or not at least from GG side.
