### ISSUE TITLE
Bug: can't save another path for UMA/Oauth Resources

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#139]
Please refer to the GIF: whenever I want to add an extra path to UMA/Oauth Resources, I get an error message and the path is not saved.

![2018-06-07_22h46_29](https://user-images.githubusercontent.com/38302725/41104444-b6737094-6aae-11e8-8226-a77912788ee5.gif)

**Comment by ldeveloperl1985** [comment]
There is an error in oxd. @yuriyz please check the logs
[oxd-server.log](https://github.com/GluuFederation/gluu-gateway/files/2089021/oxd-server.log)
[ce_dev6_oxauth.log](https://github.com/GluuFederation/gluu-gateway/files/2089024/ce_dev6_oxauth.log)

**Comment by yuriyz** [comment]
@ldeveloperl1985 as discussed in chat, oxauth throw schema violation error, which seems to be side effect of using 3.1.2 docker edition, please use 3.1.3.

**Comment by natt-tester** [comment]
I tested it yesterday with dev1 set up for ce-dev4 and wasn't able to reproduce the bug. However, after rebuilding dev1 it still occurs, so I assume dev1 is back to its previous configuration, @ldeveloperl1985 ?

**Comment by ldeveloperl1985** [comment]
@natt-tester I am unable to reproduce it in my local. Please reproduce it on dev1 and send the oxd-server and oxauth log.

**Comment by natt-tester** [comment]
[oxd-server(3).log](https://github.com/GluuFederation/gluu-gateway/files/2094093/oxd-server.3.log)
[oxauth.log](https://github.com/GluuFederation/gluu-gateway/files/2094117/oxauth.log)

![2018-06-12_22h54_31](https://user-images.githubusercontent.com/38302725/41291974-84b5e674-6e94-11e8-8814-83b8be76a990.gif)

**Comment by natt-tester** [comment]
@yuriyz maybe you're right, how can I check it? Who is responsible for ce-dev6.gluu.org configuration?

**Comment by yuriyz** [comment]
@natt-tester probably Michal or Meg, no?

**Comment by ldeveloperl1985** [comment]
Sorry, no idea. @natt-tester you can ask @yurem .

**Comment by ldeveloperl1985** [comment]
> @yurem 
Can you share list of enabled apache modules? I suspect that there is enabled security module which limit count requests from one IP, etc..
To prepare this list you can try to use command like: apachectl -M. Or on RHEL,CentoS, Fedora: httpd -M

> @ldeveloperl
output of apachectl -M
GLUU.root@ce-dev6:~# apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 evasive20_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_ajp_module (shared)
 proxy_http_module (shared)
 rewrite_module (shared)
 security2_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)

@yurem this above is output of `apachectl -M`. Please give us your suggestion

**Comment by yurem** [comment]
You should disable `evasive20_module (shared)` module and restart apache. Also there is another firewall module `security2_module (shared)`. You should also disable this if you will get same error after disabling first one.

There is alternative solution. You can update these modules default configuration to conform our requirements. @ganesh-at-wiw Can you help?

**Comment by ldeveloperl1985** [comment]
Tested and not getting this problem. free feel to open when you find it again.
