### ISSUE TITLE
Upgrade to standard oxd post-installation workflow

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#14]
GG setup asks for oxd `https URL` but gives `http` method as default. 

![image](https://user-images.githubusercontent.com/3717101/34535594-03471ca0-f088-11e7-914a-0f55a2d899f7.png)

It raises question--the http port should not be active at all on oxd. If it is, disable it.

Also, there is now a standard post installation process. See this [thread](https://github.com/GluuFederation/post-installation-setup/issues/2#issuecomment-355073170)

**Comment by ldeveloperl1985** [comment]
Tested in new build working well with https
![image](https://image.prntscr.com/image/2e1iUSYLQqmczWedVwA9EQ.png)
