### ISSUE TITLE
Bug: Hash Sum mismatch for Ubuntu 16.04

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#142]
Please refer to the screenshot -- there's a Hash Sum mismatch for Ubuntu 16.04. 

![2018-06-08_16h54_15](https://user-images.githubusercontent.com/38302725/41144443-4dd0b83e-6b40-11e8-8cf2-5435b096e9e5.png)

**Comment by adrian-gluu** [comment]
updated the repo metadata and created a new build:
https://repo.gluu.org/ubuntu/pool/main/xenial-devel/gluu-gateway_3.1.3-19~xenial+Ub16.04_amd64.deb

**Comment by natt-tester** [comment]
@adrian-gluu running all the commands for xenial installation now give me this bug after **apt install gluu-gateway**

![2018-06-12_09h56_50](https://user-images.githubusercontent.com/38302725/41263169-8e5bd178-6e28-11e8-9c85-20c2b4b6fb73.png)

**Comment by kepuss** [comment]
Package was corrupted, because not build from jenkins job. 
Fixed by creating package from job.
