### ISSUE TITLE
Bug: can't import JWKS file

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#143]
Please refer to the GIF: the import is bugged:

![2018-06-11_22h44_39](https://user-images.githubusercontent.com/38302725/41233994-5206ebcc-6dce-11e8-8130-77bcfbbe3801.gif)

**Comment by ldeveloperl1985** [comment]
We remove this as per our new design. now there is another option for create client and add client_id as custom_id in consumer.
1. Create Client
![cc](https://user-images.githubusercontent.com/2329776/47352528-b5ba5380-d6d7-11e8-9c72-1587cbd02370.png)
![cc1](https://user-images.githubusercontent.com/2329776/47352535-b94dda80-d6d7-11e8-9dde-2bdb73ca95c7.png)

2. Create consumer
![cc](https://user-images.githubusercontent.com/2329776/47352645-eef2c380-d6d7-11e8-97b5-43635e0fb9b3.png)
![cc1](https://user-images.githubusercontent.com/2329776/47352649-f1edb400-d6d7-11e8-8a09-b8a6acc103c5.png)
