### ISSUE TITLE
Bug: can't switch off Restricted APIs

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#144]
Please refer to the GIF: as discussed earlier, choosing restricted APIs and saving them seems to get stuck in the most recend build:

![2018-06-12_08h35_42](https://user-images.githubusercontent.com/38302725/41260937-e826c26e-6e1c-11e8-83f4-4ccc17fc5f05.gif)

**Comment by ldeveloperl1985** [comment]
@natt-tester  Solved. Please check

**Comment by natt-tester** [comment]
It doesn't get stuck, but it allows to save a Restricted API on with no chosen API:
![2018-06-12_22h45_45](https://user-images.githubusercontent.com/38302725/41291287-a7fa9596-6e92-11e8-8f61-784b2b8b4b8e.gif)

**Comment by ldeveloperl1985** [comment]
Done, Please check again

**Comment by natt-tester** [comment]
Agreed, it's fixed. When I choose and save some restricted APIs and then switch off the restriction, upon switching the restriction button on again, the previously chosen APIs are remembered. I don't consider it a bug, you can always change and save them.
