### ISSUE TITLE
Enhancement: add page with https://oxd.gluu.org/license/usage/

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#145]
We need a page with some useful info on the oxd-server and a button to https://oxd.gluu.org/license/usage/ in the final build. Maybe we can it to the menu under the Dashboard section, what do you say @ldeveloperl1985 ?

Pricing
Gluu Gateway uses oxd OAuth 2.0 client software to leverage the Gluu Server for client credentials and policy enforcement. oxd is a commercial software product, priced $10 per OAuth client per month. 
The first 10 oxd clients are always free, and there is a five (5) day grace period for each new client–meaning: only clients active for 5 or more days are recorded for billing purposes. 
[View your oxd usage and billing] (link to https://oxd.gluu.org/license/usage/)

It would also be good to add the info about how many oxd clients are generated for each API secured using GG.

**Comment by ldeveloperl1985** [comment]
Done. you can check the screenshot. please check it
![dash](https://user-images.githubusercontent.com/2329776/41285238-320c89e0-6e59-11e8-8ab0-8d5ea649abdc.png)

**Comment by natt-tester** [comment]
@willow9886, Meg and I concluded that it's better to put the info+button on the Dashboard so it doesn't get overlooked. What do you think?

**Comment by willow9886** [comment]
@natt-tester @ldeveloperl1985 good thinking. this looks good.
