### ISSUE TITLE
Bug: incomplete GG uninstallation

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#146]
Uninstallation of GG is incomplete now. After running apt-get remove gluu-gateway and apt-get purge gluu-gateway I see warnings and leftover files:

![2018-06-12_18h12_46](https://user-images.githubusercontent.com/38302725/41278517-5c389402-6e6d-11e8-86d6-497e14e02a6b.png)

**Comment by natt-tester** [comment]
Still occurs in the recent package, waiting for a fix.

**Comment by natt-tester** [comment]
@nikdavnik, could you take a look at why the uninstallation leaves some unnecessary files?

**Comment by ldeveloperl1985** [comment]
@natt-tester Solved DB issue. Please check it 
Remove GG step https://gluu.org/docs/gg/3.1.3/installation/

**Comment by nikdavnik** [comment]
@natt-tester this is not gluu files, its kong-community-edition and nodejs package files and have nothing to do with gluu package. 

gluu gateway is being removed with command "apt purge gluu-gateway"
"apt autoremove" command  tries to remove gluu-gateway dependency packages, i.e kong, nodejs, postgresql etc. And in this case kong and node are giving warnings that some directories can't be removed. We can't manage nodejs and kong packages, we only manage gluu-gateway package so we can't do anything regarding this. 
Anyway I think those warnings are ok, so user are notified and can manually delete those directories.

**Comment by natt-tester** [comment]
@nikdavnik, bear with me. I have just installed and uninstalled GG using `apt-get remove --auto-remove gluu-gateway` and then `apt-get purge gluu-gateway`. Here's the console output:

`root@osboxes:/opt/gluu-gateway/setup# apt-get remove --auto-remove gluu-gateway
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED
  gluu-gateway kong-community-edition lua-cjson nodejs oxd-server postgresql
0 to upgrade, 0 to newly install, 6 to remove and 394 not to upgrade.
After this operation, 268 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 175138 files and directories currently installed.)
Removing gluu-gateway (3.1.3.1-151~trusty+Ub14.04) ...
 * Stopping PostgreSQL 10 database server                                [ OK ] 
Stopping kong ...
Kong stopped
Stopping oxd-server: OK
Stopping oxd-https-extension: OK
konga stoping ...
Removing kong-community-edition (0.11.0) ...
dpkg: warning: while removing kong-community-edition, directory '/usr/local/lib/luarocks/rocks' not empty so not removed
dpkg: warning: while removing kong-community-edition, directory '/usr/local/share/lua/5.1/kong/plugins' not empty so not removed
Removing lua-cjson:amd64 (2.1.0+dfsg-2) ...
Removing nodejs (8.11.3-1nodesource1) ...
dpkg: warning: while removing nodejs, directory '/usr/lib/node_modules' not empty so not removed
Removing oxd-server (3.1.3.1-21~trusty+Ub14.04) ...
Removing postgresql (10+191.pgdg14.04+1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
root@osboxes:/opt/gluu-gateway/setup# service gluu-gateway status
10/main (port 5432): down
kong is not running ...
** ERROR: Oops! oxd server doesn't appear to be installed in /opt/oxd-server
** ERROR:  /opt/oxd-server/lib/oxd-server-jar-with-dependencies.jar is not readable!
/etc/init.d/oxd-https-extension: line 213: cd: /opt/oxd-https-extension: No such file or directory
** ERROR: Oops! oxd https extension doesn't appear to be installed in /
** ERROR:  //lib/oxd-https-extension-jar-with-dependencies.jar is not readable!
konga is not running ...
root@osboxes:/opt/gluu-gateway/setup# apt-get purge gluu-gateway
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED
  gluu-gateway*
0 to upgrade, 0 to newly install, 1 to remove and 394 not to upgrade.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 168559 files and directories currently installed.)
Removing gluu-gateway (3.1.3.1-151~trusty+Ub14.04) ...
Purging configuration files for gluu-gateway (3.1.3.1-151~trusty+Ub14.04) ...
dpkg: warning: while removing gluu-gateway, directory '/opt/gluu-gateway/setup' not empty so not removed
dpkg: warning: while removing gluu-gateway, directory '/opt/gluu-gateway/konga/assets' not empty so not removed
root@osboxes:/opt/gluu-gateway/setup# service gluu-gateway status
gluu-gateway: unrecognized service
root@osboxes:/opt/gluu-gateway/setup# service gluu-gateway status
gluu-gateway: unrecognized service
root@osboxes:/opt/gluu-gateway/setup# apt-get remove --auto-remove gluu-gateway
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'gluu-gateway' is not installed, so not removed
0 to upgrade, 0 to newly install, 0 to remove and 394 not to upgrade.
root@osboxes:/opt/gluu-gateway/setup# apt-get remove gluu-gateway
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'gluu-gateway' is not installed, so not removed
0 to upgrade, 0 to newly install, 0 to remove and 394 not to upgrade.`

I understand the issue is complex, but can we do anything about the ** ERROR** messages?

**Comment by nikdavnik** [comment]
@natt-tester here is why you see those errors.

1. at first you type **apt-get remove --auto-remove gluu-gateway** - This command will delete gluu-gateway and its dependencies (including oxd-server).

Then after deleting gluu-gateway and oxd-server you are asking for gluu-gateway status
2. **service gluu-gateway status** - And sure in this case it will print error that oxd-server files do not exist as you delete them at 1st command
(** ERROR: Oops! oxd server doesn't appear to be installed in /opt/oxd-server
** ERROR:  /opt/oxd-server/lib/oxd-server-jar-with-dependencies.jar is not readable!
/etc/init.d/oxd-https-extension: line 213: cd: /opt/oxd-https-extension: No such file or directory)
So errors here are reasonable.

3. You third command **apt-get purge gluu-gateway** - will delete gluu-gateway configuration files. After this command gluu-gateway will not be recognized, which is proved with your 4th command

4. **service gluu-gateway status**
gluu-gateway: unrecognized service

I tested once more gluu-gateway removal at everything seems fine.
Please try the following sequence for removal

1. remove gluu-gateway package - **apt remove gluu-gateway**
2. remove gluu-gateway configuration files - **apt purge gluu-gateway**
3. remove gluu-gateway dependency packages - **apt autoremove**
Please note that autoremove will delete gg dependencies i.e **kong, oxd-server, postgresql, lua-cjson, node** . From this list we only manage oxd-server package, so if autoremove prints something about node, we are not able to handle it, anyway all dependency packages are being installed from official stable repositories and they should be ok and good tested by package maintainers.

**Comment by natt-tester** [comment]
@nikdavnik, I followed the removal commands and there were no errors. However, there are still leftover files which should be removed -- as you wrote in the docs -- as "the package dependencies". So what can we do with them?

![2018-07-19_22h01_52](https://user-images.githubusercontent.com/38302725/42941498-4c82a764-8ba0-11e8-838e-4a55b6104349.png)

**Comment by nikdavnik** [comment]
@natt-tester , for postgresql packages (like postgresql-10, postgresql-client-10 etc), those are installed as dependency to postgresql itself, so postgresql in dependency for gluu-gateway and postgresql-xxx are dependencies for postgresql, and when after removing gluu-gateway we run autoremove we delete only gluu-gateway dependencies but not dependency packages' dependencies. All those packages are controlled by postgresql package and we can't do and shouldn't do anything here. This is the normal behaviour of package manager. 

for liblua5.2 its not connected to gluu-gateway, you can find this lib in fresh ubuntu14.

**Comment by natt-tester** [comment]
@nikdavnik If there's nothing we can do about this issue, let's close it.
