### ISSUE TITLE
Bug: rejecting oxd-server setup bugged

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#148]
Steps:
1. Take a new VM with Ubuntu 14.04
2. Follow the installation and setup steps for GG
3. Choose Skip when asked to configure oxd-server

Expected: The oxd-server configuration can be skipped, GG setup doesn't fail.
Actual: The oxd-server configuration can be skipped, GG setup fails.

[GG_logs.zip](https://github.com/GluuFederation/gluu-gateway/files/2093889/GG_logs.zip)
![2018-06-12_21h51_50](https://user-images.githubusercontent.com/38302725/41289256-89a0012c-6e8c-11e8-9aa4-249daec948ae.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester , please send oxd-server and oxd-http log file

**Comment by natt-tester** [comment]
[oxd-server.zip](https://github.com/GluuFederation/gluu-gateway/files/2096932/oxd-server.zip)

**Comment by natt-tester** [comment]
No bug, only when skipping the oxd-server setup, you have to make sure that you enter a valid op hostname manually. Then the installation/setup is successful and you can go to the GG panel.
