### ISSUE TITLE
BUG: Duplicate Clients Names created on OAuth registration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#149]
We should use different names to specify which clients have an oxdid, and which are used to access the oxd API's. Can we add the oxd_id to the end of the name? Like:
```
  myclient - 13149e7b-c298-4c4d-9d2b-0a640b88753e
```
Otherwise, this is confusing in oxTrust:

![image](https://user-images.githubusercontent.com/3717101/41371023-cad7a7ee-6f0e-11e8-98e1-c8b690c38452.png)

**Comment by ldeveloperl1985** [comment]
@nynymike , We are using OXD-HTTP extension and for client registration, we are using the setup_client command, it creates two clients. 
client 1 - setup client used for protection access token (client_id/client_secret). 
client 2 - oxd_id, a regular client that can be used for oxd commands.

Also, yuriyZ just added a description about two diff clients in oxd-http.
https://github.com/GluuFederation/docs-oxd-prod/blob/3.1.4/3.1.4/sources/api/index.md#set-up-client

If you are ok then please close issue?

**Comment by yuriyz** [comment]
@nynymike in 3.2.0 we are removing that second client 2 because it is confusing, we have register_site for it.

**Comment by willow9886** [comment]
@yuriyz how will this impact billing?

**Comment by nynymike** [comment]
oxd bills per client. In any case, it's a really confusing bug.

**Comment by yuriyz** [comment]
@willow9886 well, all is the same, if developer decides to use client2 then it is billed if not then it is not billed.

**Comment by nynymike** [comment]
ok, this is not a bug

**Comment by willow9886** [comment]
ok, got it. thanks @yuriyz

**Comment by ldeveloperl1985** [comment]
Assigned it to yuriyz. there is the only facility to pass one client name in the setup_client request.
```
POST /setup-client
{
    .
    "client_name": "",
    .
}
```

**Comment by yuriyz** [comment]
I propose to change name for second client via `update_site`. We anyway removing that second client in 3.2.0, so it doesn't make much sense for me to add second name handling while it is available via `update_site` command. @ldeveloperl1985 what do you think?

**Comment by yuriyz** [comment]
@ldeveloperl1985 ok, to avoid extra call from GG add `setup_client_name` to `setup_client` command in 3.1.4.
Please use it on GG side to provide valid/different names.
https://github.com/GluuFederation/oxd/issues/200

**Comment by ldeveloperl1985** [comment]
But just for the name to put extra load on kong API is not a good way.
setup_client
get_client_token
update_site

Instead of this user can easily differential client upon client_id. what you all things about this?. This is not only in consumer section, we also need to change in UMA-RS plugin, gluu-oauth2-client-auth and Konga UI login client.

**Comment by ldeveloperl1985** [comment]
Ok so we need to shift this issue to next GG milestone 3.1.4

**Comment by ldeveloperl1985** [comment]
@natt-tester Done. You can check in new GG 3.1.4 build
