### ISSUE TITLE
Dynamic enrollment should not require any claims

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#15]
![image](https://user-images.githubusercontent.com/3717101/34617054-b673d138-f1ff-11e7-884e-3263d8393084.png)

Email should not be required. You may only get a `pairwise` `sub`. Create user with even that alone.
For any other required fields (for LDAP), use random GUIDs,  For a dynamically enrolled client, you will not get any userinfo.

**Comment by ldeveloperl1985** [comment]
Solved. Tested to latest gluu-gateway-0.1.37 build.
