### ISSUE TITLE
After upgrade messed up init scripts

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#151]
![image](https://user-images.githubusercontent.com/3717101/41390969-b7ecf888-6f5d-11e8-8223-3a5701366d58.png)

1. Why was the init script konga replaced? 
2. What happened to the kong init script? 

Could be related to [GG-150](https://github.com/GluuFederation/gluu-gateway/issues/150)

**Comment by kepuss** [comment]
1. Yes, it is related.
2. Was removed because removal of those files was in postrm file.
Will be fixed together with GG-150

**Comment by natt-tester** [comment]
@nynymike, @kepuss, the kong init script is back, konga wasn't replaced. Tested in Ubuntu 14.04.

![2018-06-19_22h41_42](https://user-images.githubusercontent.com/38302725/41597898-14cdc2b8-7412-11e8-8e43-9d2a41576a7b.png)
