### ISSUE TITLE
Missing scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#152]
![image](https://user-images.githubusercontent.com/3717101/41425336-0885249c-6fc6-11e8-968c-f0bc38304fba.png)

It seems to have lost my original scope

**Comment by natt-tester** [comment]
might be connected with #139

**Comment by ldeveloperl1985** [comment]
Natt, 
Mike talking about scope which is not shown after clicking on `Add Condition` button, scope part area is missing screenshot https://prnt.sc/jv7ms4 . 

I've tried but unable to reproduce. Scopes are generated and added successfully in my case. 
Please see video: https://youtu.be/eSZCA3mJKYo

@natt-tester please check it and let me know if you reproduce it and any other problem.

**Comment by natt-tester** [comment]
@nynymike, @ldeveloperl1985, I have tried to reproduce this issue several times, but it was unsuccessful. I always get the behavior shown in the GIF. Mike, could you please give us some reproduction steps for this one?  

![2018-06-15_21h23_43](https://user-images.githubusercontent.com/38302725/41465869-3aa389f0-70e3-11e8-9ba6-056564fbdc0a.gif)

**Comment by nynymike** [comment]
It works when you first add it. But go go back to the API view, and view the API. Then you will see all the scopes dissappeared

![image](https://user-images.githubusercontent.com/3717101/41612136-9e802132-73b7-11e8-9f13-1c88173b4297.png)

**Comment by ldeveloperl1985** [comment]
@nynymike I've solved this issue and updated on demo server. please test it

**Comment by natt-tester** [comment]
@nynymike, @ldeveloperl1985 -- I haven't been able to reproduce it in Chrome or Firefox with the new build.
