### ISSUE TITLE
Which way is ok for update client secret expire time for all Clients in GG?

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#153]
The problem is that **`client_id`** and **`client_id_of_oxd_id`** expire after a day. And we have no convenient way o update it. Currently, In GG, we only store and show the **`oxd_id`**

There are two ways
1. To store and show **`setup_client_oxd_id`** in every section of GG-clients(Clients: login client, gluu-oauth2-rs plugin client, gluu-oauth2-client-auth plugin client, consumers client).
[Note: Currently, In GG, we only store and show the **`oxd_id`**]. The user wants both ids to update client expire time.

2. To add https://github.com/GluuFederation/oxd/issues/198 feature in oxd 3.1.3.1.

@nynymike , @willow9886 and all please give me your suggestion for this. which way is good?

Just for info: Related ticket to client expire time update
https://support.gluu.org/other/5596/setup-for-gluu-gateway-with-non-expiring-client-credentials/

**Comment by ldeveloperl1985** [comment]
I've added `setup_client_oxd_id` in GG(done in issue https://github.com/GluuFederation/gluu-gateway/issues/154) because the user needs to track client id of oxd id in oxd e-comm portal. oxd e-comm portal issue https://github.com/GluuFederation/ecommerce-python/issues/35.

If anyone has any suggestion or idea then please provide.

**Comment by nynymike** [comment]
There is no way for the client to update the registration. It's up to the OP how long to keep the client entry.

There are a few solutions:

1. **Short term** Recommend setting the client expiration longer. In oxAuth, `dynamicRegistrationExpirationTime` can be set to one year: `31,540,000`

2. ** Long term** In Gluu Server 4.0, we will support OAuth software statements. So the OP could issue a software statement (i.e. signed JWT) that could be presented at registration time, specifying a certain expiration (which dynamic client registration would have to respect).
