### ISSUE TITLE
Show client_id_of_oxd_id in consumer credential section

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#154]
Show `client_id_of_oxd_id` insted of `client_id` in consumer credential section.

![clientshowid](https://user-images.githubusercontent.com/2329776/41538491-2d5b72f6-7329-11e8-87c4-009475fe7cc6.png)

**Comment by ldeveloperl1985** [comment]
Done. Please check

**Comment by ldeveloperl1985** [comment]
@natt-tester check now. I've made changes on every place.
1. On dashboard
![154dashboard](https://user-images.githubusercontent.com/2329776/41543492-886b855e-7334-11e8-83f6-528aa6837e29.png)

2. On UMA API
![154umars](https://user-images.githubusercontent.com/2329776/41543511-90d2fef2-7334-11e8-89c9-443fdf89f336.png)

3. Consumer credential add
![154consumeradd](https://user-images.githubusercontent.com/2329776/41543531-9a97e128-7334-11e8-95ea-4bb16a901601.png)

4. Consumer list page
![154consumerlist](https://user-images.githubusercontent.com/2329776/41543547-a43d1dc4-7334-11e8-95a1-564f596edd52.png)

**Comment by natt-tester** [comment]
@ldeveloperl1985 I see the update and I have two questions:
1. If it's added to Consumer creation section, why is the table view in details with only 2, not 4 credentials? We inform the user that the only disappearing credential is the client secret, but in fact now it's both client secret AND client id. Apart from that, we should stick to one name for the added oxd client id, so please change "Client id of OXD id" to "oxd client id" to avoid any confusion.
2. What about the enhancement in #137? Are we going to have it for 3.1.3? Right now there's no milestone set.

**Comment by ldeveloperl1985** [comment]
@natt-tester 
1. I've set `Client id of OXD id` title everywhere because it is similar to oxd key so it is easy to understand. And removed client id from list and added in edit popup.

![154consumeredit](https://user-images.githubusercontent.com/2329776/41593328-4cdaed50-73dd-11e8-8695-63b2abb91e27.png)
![154dashboard](https://user-images.githubusercontent.com/2329776/41593336-51ed61f6-73dd-11e8-872a-8fcede1b05ac.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester I've done changes, also Michal made a new build. so please check it

**Comment by natt-tester** [comment]
@ldeveloperl1985, it is changed everywhere indeed, but the Consumer credentials view is cut -- see the screen. Also, please change the name of the field to "Client Id of OXD Id" to stay consistent with the rest :)

![2018-06-19_23h23_57](https://user-images.githubusercontent.com/38302725/41600273-d09c13ae-7418-11e8-8b53-0b980ea86da9.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester  Check again screenshot. for Consumer credentials, you can easily select with the mouse
![oxdidname](https://user-images.githubusercontent.com/2329776/41600984-dfd11f6e-73f4-11e8-9c18-1efadd993a68.png)

**Comment by natt-tester** [comment]
The credentials are added, but there's a blocker issue in #159.
