### ISSUE TITLE
Enhacement: improve table display

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#155]
Please refer to the GIF and improve the display of the DASHBOARD table in zoom <= 90%.

![2018-06-19_22h49_18](https://user-images.githubusercontent.com/38302725/41598693-4eaba70a-7414-11e8-93f3-bb08a8b0da6d.gif)

**Comment by ldeveloperl1985** [comment]
Solved, by removing pricing section.
