### ISSUE TITLE
Ambiguous Error message

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#156]
I was specifying the SeCURITY, and when I hit add, I got this message:

![image](https://user-images.githubusercontent.com/3717101/41612348-331690ec-73b8-11e8-8b7f-3bd7a54781f2.png)

It turns out I had GET twice in my policy, which was my bad. However, nothing was highlighted, so I had no idea where to look for the error. Not good UX.

**Comment by willow9886** [comment]
@natt-tester can you also review error messages with Meg and improve the English?

**Comment by nynymike** [comment]
Also, the fields throwing the error need to be highlighted

**Comment by natt-tester** [comment]
@willow9886, @nynymike I'm on it.

**Comment by ldeveloperl1985** [comment]
@natt-tester and @nynymike please test it. I've updated it on demo server.

**Comment by natt-tester** [comment]
@ldeveloperl1985, @nynymike -- I think it's down now...?

**Comment by ldeveloperl1985** [comment]
I've tracked all other errors and display message according to that

1. For empty field and highlighted
![img1](https://user-images.githubusercontent.com/2329776/41717978-25fc8624-7579-11e8-8bc9-1fc7fe471919.png)

2. For duplicated method
![img2](https://user-images.githubusercontent.com/2329776/41718033-530e8df6-7579-11e8-8464-4e8238bba921.png)
![img21](https://user-images.githubusercontent.com/2329776/41718079-7cd6635c-7579-11e8-8b9b-66c66b0f2fe5.png)

3. For duplicate path
![img3](https://user-images.githubusercontent.com/2329776/41718112-98445aa4-7579-11e8-989b-db928fa9df91.png)
Same for OAuth expression

**Comment by ldeveloperl1985** [comment]
@natt-tester I've checked. Same issue https://github.com/GluuFederation/gluu-gateway/issues/139. 
In oxd log:
```
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /.well-known/uma2-configuration
on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at ce-dev6.gluu.org Port 443</address>
```

**Comment by ldeveloperl1985** [comment]
I've tried the same request after two minutes and it works.

**Comment by yurem** [comment]
Can you share list of enabled apache modules? I suspect that there is enabled security module which limit count requests from one IP, etc..

You can try to use command like: `apachectl -M`. Or on RHEL,CentoS, Fedora: `httpd -M`

**Comment by ldeveloperl1985** [comment]
@yurem output of `apachectl -M`
```
GLUU.root@ce-dev6:~# apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 evasive20_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_ajp_module (shared)
 proxy_http_module (shared)
 rewrite_module (shared)
 security2_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)
```

**Comment by natt-tester** [comment]
@ldeveloperl1985, @yurem, what's the status of this issue?

**Comment by ldeveloperl1985** [comment]
Already solved the `Ambiguous Error message` issue. Now it related to  `403 Forbidden` problem, same issue https://github.com/GluuFederation/gluu-gateway/issues/139, let move the discussion to issue-139.
@yurem, please reply your suggestion in https://github.com/GluuFederation/gluu-gateway/issues/139
