### ISSUE TITLE
Enhancement: change string in error message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#157]
Please refer to the marked strings and change them to "Requires at least one restricted API" and the others to "APIs" (no apostrophe).

![2018-06-20_12h21_17](https://user-images.githubusercontent.com/38302725/41633941-b6d7eea4-7484-11e8-921f-bbb093621abc.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester solved. please test it

**Comment by ldeveloperl1985** [comment]
It is ok. It executes validation step by step. You first enable restricted API without APIs selection so it shows the restricted API validation first

**Comment by natt-tester** [comment]
@ldeveloperl1985 I agree that it's step by step, but take a look at the message -- it's the old one from before the string change, so please change it everywhere in the code.

**Comment by ldeveloperl1985** [comment]
Ok done ![image](http://i.prntscr.com/9JJxXwZgQJOa-1KQTpkI5w.png)
