### ISSUE TITLE
Bug: too many created groups

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#158]
Please look at the GIFs and solve the following issues: 
1. Limit the creation of groups to 1 each time. 
2. Do we really need these two ADD GROUP buttons? 
3. Shouldn't the inactive field text say "Enter groups"?
4. There's a success message when you enter and save a non-existent group, but it's not saved. It should be saved and visible. I think it's related to #152, HAPPENS ONLY IN CHROME!

![2018-06-20_15h43_45](https://user-images.githubusercontent.com/38302725/41639553-9da16c86-74a1-11e8-95d5-95f72f675788.gif)
![2018-06-20_15h54_15](https://user-images.githubusercontent.com/38302725/41639918-293d574a-74a3-11e8-8c13-49b08cabc752.gif)
![2018-06-20_15h52_03](https://user-images.githubusercontent.com/38302725/41639925-2e22fada-74a3-11e8-89b0-7e8742091851.png)

**Comment by natt-tester** [comment]
I think we should shift this one to 3.1.4 as @ldeveloperl1985 says she's managed to solve all but the group creation issue. Is it ok, @nynymike ?

**Comment by ldeveloperl1985** [comment]
@natt-tester I've solved the multiple group problem so please check it.

**Comment by natt-tester** [comment]
@ldeveloperl1985 is it on dev1 already? I've just checked the group creation and the behavior seems the same:
![2018-07-09_20h33_01](https://user-images.githubusercontent.com/38302725/42445891-da106698-83b7-11e8-8790-49705ae01940.gif)

Please remember to check the default radio button ;)

**Comment by ldeveloperl1985** [comment]
Currently, it is not in build but you can test it by replace 
1. https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3/konga/assets/js/app/apis/controllers/manage-uma-rs-plugin-controller.js  --> /opt/gluu-gateway/konga/assets/js/app/apis/controllers/

2. https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3/konga/assets/js/app/apis/views/manage-uma-rs-plugin.html --> /opt/gluu-gateway/konga/assets/js/app/apis/views/

**Comment by natt-tester** [comment]
@ldeveloperl1985 The multiple groups are indeed missing, but now I can't save the security settings:

[2018-07-11_16h46_37.zip](https://github.com/GluuFederation/gluu-gateway/files/2183231/2018-07-11_16h46_37.zip)
#185 mentions it, too.

**Comment by natt-tester** [comment]
It's done.
