### ISSUE TITLE
Bug: no validation for Consumer Plugin name field

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#160]
Please watch the video and implement the validation for the name field + the suggested validation error message. Now it sets "gluu-oauth2-client-auth" as Customer name when the field is sent as empty.

![2018-06-20_21h21_55](https://user-images.githubusercontent.com/38302725/41655541-89ea1a06-74d0-11e8-8b0b-50d93659563b.png)
[2018-06-20_21h20_41.zip](https://github.com/GluuFederation/gluu-gateway/files/2119049/2018-06-20_21h20_41.zip)

**Comment by ldeveloperl1985** [comment]
@natt-tester solved. please test it

**Comment by natt-tester** [comment]
It still requires work: there's no highlight or meaningful message such as "This field is required":

![2018-06-21_16h18_58](https://user-images.githubusercontent.com/38302725/41701266-34fb56fa-756f-11e8-98c1-485436ffa642.gif)

**Comment by ldeveloperl1985** [comment]
I see on dev1. There is an old code. Please check with the latest code.

**Comment by natt-tester** [comment]
@ldeveloperl1985 It doesn't work with the latest code either:
![2018-06-21_17h57_31](https://user-images.githubusercontent.com/38302725/41705683-0d8b6994-757d-11e8-92c7-aa908dab54c5.gif)

**Comment by natt-tester** [comment]
@ldeveloperl1985 Ok, clearing the cache did the trick. I see that validation is added, but it's not consistent with the rest of the validation errors: there's no highlight or pop-up in the upper right corner saying that the field is required. It's highlighted only when the name is given and then deleted. I think it still needs work.

**Comment by ldeveloperl1985** [comment]
Done. Please check again

**Comment by natt-tester** [comment]
Ok, it's highlighted. There's no pop-up message, but I guess we'll have it in 3.1.4.
