### ISSUE TITLE
Blocker: can't add Gluu AOauth2 plugin

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#162]
@ldeveloperl1985, I can't add the plugin in the GG UI:
![2018-06-21_15h18_28](https://user-images.githubusercontent.com/38302725/41700657-710031b4-756c-11e8-8bff-9a9144e75197.gif)

**Comment by ldeveloperl1985** [comment]
Please test with the latest code.

**Comment by natt-tester** [comment]
It works with the latest code.
