### ISSUE TITLE
Enhancement: highlight semi-required fields

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#163]
It would be a good idea to highlight the three semi-required fields when there's no input for any of them:

![2018-06-21_15h16_01](https://user-images.githubusercontent.com/38302725/41700768-1b0edcd2-756d-11e8-868f-c9692e154da2.gif)

Maybe a lighter shade of red?

**Comment by ldeveloperl1985** [comment]
Done.
![cc](https://user-images.githubusercontent.com/2329776/46143516-d4affc00-c277-11e8-9191-c5996ba7fc7e.png)
