### ISSUE TITLE
Enhancement: add error message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#164]
Whenever the user misses a required field, it's good to have the field highlighted and a pop-up error message with "This field is required":

![2018-06-21_16h37_07](https://user-images.githubusercontent.com/38302725/41701951-b7cf27da-7571-11e8-9e46-df71841b2e56.gif)

**Comment by ldeveloperl1985** [comment]
@natt-tester  This is from Kong side. This error message return from Kong API **username is required** so it is ok
