### ISSUE TITLE
Enhancement: change strings in Consumer Credentials 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#165]
@ldeveloperl1985, please check the suggestions and add them to the Consumer Credentials:

![2018-06-20_20h19_55](https://user-images.githubusercontent.com/38302725/41707650-f78a14a6-7581-11e8-8084-e967af703a12.png)

**Comment by ldeveloperl1985** [comment]
Done. please check in screenshot
![spelmis](https://user-images.githubusercontent.com/2329776/41708502-67a4feb4-755e-11e8-8b1f-a758695808f0.png)

**Comment by natt-tester** [comment]
@ldeveloperl1985 I see that I missed a few... sorry!

![41708502-67a4feb4-755e-11e8-8b1f-a758695808f0](https://user-images.githubusercontent.com/38302725/41711435-7311cde0-758b-11e8-8d9b-c48287f3adbd.png)

**Comment by ldeveloperl1985** [comment]
Done. please check screenshot
![engtext](https://user-images.githubusercontent.com/2329776/41712601-8d75af6c-7568-11e8-837b-0c11f344befc.png)

**Comment by natt-tester** [comment]
Agreed, it's done.
