### ISSUE TITLE
Enhancement: highlight required fields upon validation 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#166]
Please take a look at the behavior of Restricted APIs -- is there a way to always highlight the section an error message refers to? It would be great for the UX in all GG sections.
![2018-06-21_18h40_28](https://user-images.githubusercontent.com/38302725/41707958-afb8a7ae-7582-11e8-8540-95849408c261.gif)

**Comment by ldeveloperl1985** [comment]
As per our new design, we don't need this. There is kong [ACL](https://docs.konghq.com/hub/kong-inc/acl/) plugin to restrict access for API to consumer.
