### ISSUE TITLE
Enhancement: add Client Id of OXD Id to description

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#167]
Please change the string so that it mentions 4 credentials and includes the Client Id of OXD Id.

![2018-06-21_18h55_28](https://user-images.githubusercontent.com/38302725/41711148-c6cf44b8-758a-11e8-91b7-367bb0e6282c.png)

**Comment by ldeveloperl1985** [comment]
Done. please check screenshot
![engtext](https://user-images.githubusercontent.com/2329776/41712595-8aa58a6e-7568-11e8-9c81-8379e28fb811.png)

**Comment by natt-tester** [comment]
Agreed, it's done.
