### ISSUE TITLE
Show setup_client_oxd_id

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#168]
Show setup_client_oxd_id. requested from https://github.com/GluuFederation/ecommerce-python/issues/35

**Comment by ldeveloperl1985** [comment]
Done. Please check.
![img1](http://i.prntscr.com/66uN9OhqQxepS-A6vt9rng.png)
![img2](http://i.prntscr.com/Ojnd049GQuWASXiPbK4Q5A.png)
![img3](http://i.prntscr.com/NX0LfD33Tu6B4unAJiP0ZQ.png)
![img4](http://i.prntscr.com/h16qcJ2CQB2ejh-aEHCBUA.png)
![img5](http://i.prntscr.com/ZeVZLfIyQHas3TvMiOPXHA.png)

**Comment by natt-tester** [comment]
Agreed, it's shown in all of these views.
