### ISSUE TITLE
Enhancement: improve logic/UX behind consumer credentials

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#169]
When I create a new set of Consumer credentials, but enter an already created e.g. Setup client OXD Id, there's no validation or the validation is bugged because it does create a set of credentials, but they are entiely new values.

The only way to use old credentials seems to be replacing an already existing set with them. 
It needs further testing because there are plenty of factors to look at here.

**Comment by ldeveloperl1985** [comment]
Done. Now user can add client using existing client credentials. As per our new design user only need to enter `client_id` and `client_secret`(No need of `setup client oxd id`).

New design for create OP Client.
![cc](https://user-images.githubusercontent.com/2329776/46141615-150c7b80-c272-11e8-9901-863228d36400.png)
