### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#17]
Dashboard shows plugins:
![image](https://user-images.githubusercontent.com/3717101/34630424-a64a1baa-f231-11e7-88d0-bb546447305d.png)

But none are here:
![image](https://user-images.githubusercontent.com/3717101/34630432-aeee335e-f231-11e7-977b-24f849747d57.png)

**Comment by ldeveloperl1985** [comment]
Same as https://github.com/GluuFederation/gluu-gateway/issues/10. Issue solved.
@nynymike  This window only shows added plugins. If you want other plugins then click on + ADD GLOBAL PLUGINS button.
Doc description: https://github.com/GluuFederation/gluu-gateway#5-plugins
