### ISSUE TITLE
Enhancement: close dialog windows by clicking OK

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#170]
Please refer to the Credentials window and how easily it can be closed by mistake when the user clicks anywhere outside it. It'd be a good idea to change the closing way to clicking the OK/SUBMIT button only.

![2018-06-25_15h45_55](https://user-images.githubusercontent.com/38302725/41832447-6d6b1be2-788f-11e8-84b8-e3b86cf61025.gif)

**Comment by ldeveloperl1985** [comment]
Done. Window only closes when user click on ok button. As per our new design flow, now client add option is in consumer section direct.
![cc](https://user-images.githubusercontent.com/2329776/46083080-37dd5800-c1be-11e8-8b06-1a91efb5b184.png)
