### ISSUE TITLE
Enhancement: remove info about inactive Settings

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#172]
Please refer to the screenshot and remove the hint about the disabled Settings:

![2018-06-28_11h26_19](https://user-images.githubusercontent.com/38302725/42007960-65658688-7ac6-11e8-8804-f9f3f1a7b878.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester  Done. Please Check

**Comment by natt-tester** [comment]
Agreed, it's done.
