### ISSUE TITLE
Enhancement: change pop-up color to red

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#173]
Please refer to the screenshot and change the color of the pop-up message to red for an unresponsive/unreachable node:

![2018-06-28_14h12_07](https://user-images.githubusercontent.com/38302725/42013119-11a2464e-7adf-11e8-90ce-de0f1f28f9f0.png)

**Comment by ldeveloperl1985** [comment]
Yellow color is ok because it is not error, it is warning for particular kong node, which is not active, so this yellow color for warning is ok.
