### ISSUE TITLE
Enhancement: change error message to pop-up

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#176]
Please watch the GIF -- I think we should be consistent with the green pop-ups for success and red ones for failure. Having said that, I believe we should change the current error messages to pop-ups to make them more visibe and clear.

![2018-06-28_16h47_01](https://user-images.githubusercontent.com/38302725/42017781-90c1ab40-7af3-11e8-9262-bc09fa220a54.gif)

**Comment by ldeveloperl1985** [comment]
Done in branch version_4.0.0
