### ISSUE TITLE
Enhancement: change strings in Upstreams

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#177]
@ldeveloperl1985 , please refer to the picture and advise: I think we should change the instructions to "To disable a target, post a new one with weight=0 or click on the DISABLE button next to its name, which will automatically assign 0 to its weight."

As the change is quite logical, I think we should also alter the DELETE string to DISABLE for the button(s).

![2018-06-29_12h14_25](https://user-images.githubusercontent.com/38302725/42070612-8f357ab6-7b9a-11e8-9b93-44383e8fca3e.png)

**Comment by ldeveloperl1985** [comment]
Done
