### ISSUE TITLE
Add dynamic path facility in UMA resources and OAuth scope.

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#179]
Currently, there is the only a static path feature. 

Example: Path: /todos Method: GET, POST, PUT, DELETE. Mostly PUT and DELETE APIs are dynamic.
```
HTTP method: DELETE
/todos/[id]
``` 

So whenever user request with dynamic path, plugin always returns "401/Unauthorized - Path is not registered". Because this dynamic path is not registered.

**Comment by yuriyz** [comment]
We have ticket opened on `uma-rs` project to add support for wildcards https://github.com/GluuFederation/uma-rs/issues/1.

However there can be quick workaround to it, instead of dynamic part GG can register placeholder, for example: `/todos/[id]` -> `/todos/_dynamic`. So we statically bind generated part to `_dynamic` placeholder. At design time GG on UI should force user specify dynamic part of the url.

@nynymike I guess we need you input whether it is acceptable workaround.

**Comment by yuriyz** [comment]
Agreed, lets apply parent rule.

**Comment by ldeveloperl1985** [comment]
@nynymike @yuriyz  I've added parent rule support. There is no change from the UI side. 
Example:

If the register path is `/folder1`
```
[
  {
    "path": "/folder1",
    "conditions": [
      {
        "httpMethods": [
          "GET",
          "POST",
          "DELETE",
          "PUT"
        ],
        "scope_expression": {
          "rule": {
            "and": [
              {
                "var": 0
              }
            ]
          },
          "data": [
            "Admin"
          ]
        }
      }
    ]
  }
]
```

then allow ticket and access for paths:
```
GET /folder1/32123434
GET /folder1/folder2/dsdsgfg3434
GET /folder1/one/two/three
GET /folder1?id=dfdf5454fg
GET /folder1?id=dggfg&page=1&top=10

Same for all the HTTP method
```

Deny path
```
GET /folder11111
GET /folder1111/folder2
GET /folder2
```

Is this ok?

**Comment by nynymike** [comment]
What if there is a sub-folder /folder1/folder2 that has different rules (e.g. perhaps allow all for GET)

**Comment by ldeveloperl1985** [comment]
I still need to work on that. I'll work on the sub-folder different rule.

**Comment by ldeveloperl1985** [comment]
@nynymike I've made changes. The user can apply the folder levels of rules.

Example:
If User define some rules as given below
```
Rule1 for path GET /root                  {scope: a, b}
Rule2 for path GET /root/folder1          {scope: c}
Rule3 for path GET /root/folder1/folder2  {scope: d}
```

then allow ticket and access for paths and rule:
```
GET /root     --> Apply Rule1
GET /root/1    --> Apply Rule1
GET /root/one    --> Apply Rule1
GET /root/one/two  --> Apply Rule1
GET /root/two?id=df4edfdf  --> Apply Rule1

GET /root/folder1   --> Apply Rule2
GET /root/folder1/1   --> Apply Rule2
GET /root/folder1?id=dfdf454gtfg  --> Apply Rule2
GET /root/folder1/one/two  --> Apply Rule2
GET /root/folder1/one/two/treww?id=w4354f  --> Apply Rule2

GET /root/folder1/folder2/1    --> Apply Rule3
GET /root/folder1/folder2/one/two  --> Apply Rule3
GET /root/folder1/folder2/dsd545df   --> Apply Rule3
GET /root/folder1/folder2/one?id=fdfdf  --> Apply Rule3

SAME FOR ALL THE HTTP METHODS
```

Deny path: because not register and no rule
```
/rootttt
/temp
/other
```

**Comment by nynymike** [comment]
Looks good.

**Comment by ldeveloperl1985** [comment]
Ok thanks,
@natt-tester @kepuss you can test it by taking the update from branch version_3.1.3.

Replace all the files as given below.

[gluu-oauth2-client-auth](https://github.com/GluuFederation/gluu-gateway/tree/version_3.1.3/gluu-oauth2-client-auth/kong/plugins/gluu-oauth2-client-auth) replace in `/usr/local/share/lua/5.1/kong/plugins/gluu-oauth2-client-auth`

[gluu-oauth2-rs](https://github.com/GluuFederation/gluu-gateway/tree/version_3.1.3/gluu-oauth2-rs/kong/plugins/gluu-oauth2-rs) replace in `/usr/local/share/lua/5.1/kong/plugins/gluu-oauth2-rs`

**Comment by natt-tester** [comment]
@ldeveloperl1985, @kepuss, @nynymike, I've tested several combinations with various children, scopes, rules and methods. Every single one was protected in the right way and I see no bugs in the fix.

**Comment by altexy** [comment]
Meghna Joshi @ldeveloperl1985  gluu 8:15 PM   

> Example: resource are `/country/[contry_id]/state/[state_id]/city/[city_id]`

> If he register `/country` then whole the resources under `/country` folder will be protected 
> Example: `/contry/1/state/2/..`

> But when he want to add security on state folder `/country/[contry_id]/state/` where `[contry_id]` is dynamic value then it will not work. we need to work for this. we need to add wildcard facility for the dynamic routes.

Maybe we would return to @yuriyz original offer https://github.com/GluuFederation/gluu-gateway/issues/179#issuecomment-403015705?

We may define a placeholder which allows any value in an uri part.

IMO the exact match must have the preference on wildcard match.

We may implement the same logic for the UMA and Oauth scope expression.

From UI side we may use a predefined string like @yuriyz offered or special UI wildcard element.

@ldeveloperl1985 @yuriyz @nynymike please comment

**Comment by ldeveloperl1985** [comment]
I agreed, we can use the predefined string as yuriyz offered.

**Comment by altexy** [comment]
For simplicity, I would offer to use `*` placeholder for wildcard element, but `*` character is allowed in URI.
`?` character is not allowed in an URI so we may safely use it as a placeholder.

`/country/?/state/?/city`

**Comment by ldeveloperl1985** [comment]
Agreed :+1:

**Comment by nynymike** [comment]
? Is not good... Any url with params will have a *

**Comment by altexy** [comment]
@nynymike when we parse a path we use normalized path - with relative paths resolved and without params.

**Comment by altexy** [comment]
Would it be useful if we give to an admin the way to distinguish exact path match and all subfolder match?

At the moment we implement all subfolder match. So `/path/folder/file` also matches `/path/folder/file/whatever`.

We cannot specify an exact match with the current implementation.

**Comment by nynymike** [comment]
Regular expression would be nice.

**Comment by ldeveloperl1985** [comment]
Done
