### ISSUE TITLE
Bug: add validation to Upstream slots

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#180]
When you enter a random string in the Slots field, it gets an error message, but gets saved either way and defaults to 100. Please fix it:

[2018-07-09_19h24_50.zip](https://github.com/GluuFederation/gluu-gateway/files/2175502/2018-07-09_19h24_50.zip)

**Comment by ldeveloperl1985** [comment]
Done and merge in branch version_4.0.0
