### ISSUE TITLE
Enhancement: disable OAuth scope security with UMA and Mix

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#181]
Please refer to the picture: it's possible to enable the OAuth scope security with UMA and Mix in the UI. 

![enh](https://user-images.githubusercontent.com/38302725/42444041-78bf4ef4-83b2-11e8-98e9-a6d48d3da96a.png)

**Comment by ldeveloperl1985** [comment]
@natt Done. Please make a new build and check. OAuth scope security is only allow in OAuth mode

**Comment by natt-tester** [comment]
Agreed, it's done. Check both with Postman and in the UI:

![2018-07-17_20h25_01](https://user-images.githubusercontent.com/38302725/42812116-e99e296c-89ff-11e8-862b-609bc392deca.png)
![2018-07-17_20h27_42](https://user-images.githubusercontent.com/38302725/42812118-ea728bbc-89ff-11e8-9b93-2b600fd3c273.png)

[2018-07-17_19h52_30.zip](https://github.com/GluuFederation/gluu-gateway/files/2201259/2018-07-17_19h52_30.zip)
