### ISSUE TITLE
Enhancement: add info to SECURITY

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#182]
Please add the following string in red to the SECURITY section:

![2018-07-09_20h01_36](https://user-images.githubusercontent.com/38302725/42444579-ca7df56e-83b3-11e8-9139-8a8ada074bfc.png)

**Comment by ldeveloperl1985** [comment]
Done
![textoauthchange](https://user-images.githubusercontent.com/2329776/42505475-7015dc3c-845c-11e8-924a-37fffe20e805.png)

**Comment by natt-tester** [comment]
Agreed, it's done.
