### ISSUE TITLE
Enhancement: SECURITY view

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#183]
Please introduce the following changes:
1. When the user wants to save the OAuth scope security, they must first remove the path in UMA. As a user I want to be able to save one type of path+security without paying attention to the other one
2. When you have an OAuth scope security only, the irrelevant section of the Plugin Details should be hidden
3. Align the columns of the tables in the view and maybe give them white headers?

**Comment by ldeveloperl1985** [comment]
@natt-tester I've updated the changes in SECURITY view. Please make a new build and check

**Comment by ldeveloperl1985** [comment]
Done. Please check it. You can see output in the screenshot
![table-align](https://user-images.githubusercontent.com/2329776/42815278-98cd3c00-89e4-11e8-8307-6a3a96e22694.png)

**Comment by natt-tester** [comment]
Looks good :)
