### ISSUE TITLE
Update setup script to setup plugins and add plugin in GG package

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#184]
@adrian-gluu @nikdavnik please add plugins in `/opt/gluu-gateway/plugins` path. There are two plugin

1. [gluu-oauth2-client-auth](https://github.com/GluuFederation/gluu-gateway/tree/version_3.1.3.1/gluu-oauth2-client-auth/kong/plugins/gluu-oauth2-client-auth)
2. [gluu-oauth2-rs](https://github.com/GluuFederation/gluu-gateway/tree/version_3.1.3.1/gluu-oauth2-rs/kong/plugins/gluu-oauth2-rs)

I'll update the setup script to move plugins from GG package to kong/plugins folder.

**Comment by ldeveloperl1985** [comment]
@adrian-gluu @nikdavnik  I've updated the script so please make new GG 3.1.3.1 build. Take update from version_3.1.3 branch

**Comment by ldeveloperl1985** [comment]
Works in my case.
@natt-tester Please check this issue.

**Comment by natt-tester** [comment]
The new dev1 build is up and running. The plugins are in the right folder, so I agree it's fixed:

![clipboard - july 12 2018 10_46 pm](https://user-images.githubusercontent.com/38302725/42634220-fa6f8f84-8625-11e8-9c86-155e3fb24613.png)
