### ISSUE TITLE
Bug: 500 when making API call

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#187]
Make a call to an API protected with an OAuth scope with the right scope in the token. The result is 500:

![2018-07-11_23h01_19](https://user-images.githubusercontent.com/38302725/42573079-77f3d190-855e-11e8-9266-bfab2bca9deb.png)

**Comment by ldeveloperl1985** [comment]
@natt-tester I've solved this. Please take update and check

**Comment by natt-tester** [comment]
Agreed, it's done.

**Comment by natt-tester** [comment]
It's done on GG's side.
