### ISSUE TITLE
GG UMA "not" scope expression

### ISSUE THREAD

**Issue by kepuss** [GluuFederation/gluu-gateway#191]
Configuration of UMA Resource in GG allows to configure multiple scopes with "not" expression which throws exception in oxAuth.
Example:
```
"scope_expression": {
          "rule": {
            "not": [
              {
                "var": 0
              },
              {
                "var": 1
              }
            ]
          },
          "data": [
            "passing_scope",
            "failing_scope"
          ]
        }
```
Execution of such expression fails in oxAuth
```
2018-07-13 12:09:10,818 ERROR [qtp366590980-19] [org.xdi.oxauth.uma.service.UmaExpressionService] (UmaExpressionService.java:111) - Failed to evaluate jsonlogic expression. Expression: {"data":["passing_scope","failing_scope"],"rule":{"not":[{"var":0},{"var":1}]}}, resourceDn: oxId=eb370eec-5483-4d06-905b-b868f7e41d49,ou=resources,ou=uma,o=@!DBE5.84F8.631A.9172!0001!CD07.49BE,o=gluu
```

Even in case of having only one scope GG is creating array:
```
 "scope_expression": {
          "rule": {
            "not": [
              {
                "var": 0
              }
            ]
          },
          "data": [
            "failing_scope"
          ]
        }
```
Configuration screen:
![screenshot](https://user-images.githubusercontent.com/11611679/42692179-4c96b52a-869a-11e8-91d2-0d9dca6cb861.png)

@nynymike @ldeveloperl1985 @yuriyz is there any scenario when "not" can be used in scope_expression or we should disable this option?

**Comment by yuriyz** [comment]
It is not clear what `not` means here. Is it translated to valid negative operator ('!') in expression?

invalid -> `{"not" : true } `
valid -> `{ "!" : true }`

you can try it in playground here: http://jsonlogic.com/play.html
supported operations are here: http://jsonlogic.com/operations.html

**Comment by yuriyz** [comment]
Expression in ticket description is invalid according to jsonlogic.

**Comment by ldeveloperl1985** [comment]
Done. I've changed the operator `not` to `!`.  @kepuss Please make a new GG build and check

**Comment by kepuss** [comment]
@ldeveloperl1985 Now expression is evaluated,
however: @yuriyz I'm a bit confused with jsonlogic http://jsonlogic.com/operations.html#-4
It states that "Logical negation (“not”). Takes just one argument." and there are 2 examples:
- array with one element inside
- and another example with just one element
So documentation is not clear about multiple values in array. I tried in playground and it seems like values in array are evaluated with "and" operator. oxAuth also evaluates using and inside array but I'm wondering if we should add comment in docs about it?

**Comment by yuriyz** [comment]
It looks not very strict but still acceptable. As long as we evaluate everything as it is declared in jsonlogic we are good. Not sure why we need to add notes if it declared inside jsonlogic docs already.

**Comment by kepuss** [comment]
I was just thinking, that it can be helpful to add "not" example (because "and" and "or" exist in docs)
Moreover, I couldn't find in docs any reference that we are using jsonlogic. ( I checked: 
https://gluu.org/docs/ce/admin-guide/uma/#register-resource-with-scope_expression
https://gluu.org/docs/gg/plugin/gui/#protection-document)

**Comment by yuriyz** [comment]
@kepuss we have it in oxd docs but somehow missed in CE docs. Just added it. Would you please add it to GG docs too?

**Comment by kepuss** [comment]
Done thanks
