### ISSUE TITLE
Enhancement: change string in setup process

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#192]
It is not only client_id and client-secret, so it should be "enter existing client credentials manually"

![2018-07-18_15h22_49](https://user-images.githubusercontent.com/38302725/42861499-968cd67a-8a9e-11e8-9b4f-ca8242c5a2b9.png)

**Comment by ldeveloperl1985** [comment]
Done. Please check.

**Comment by natt-tester** [comment]
Agreed, it's done:

![2018-07-18_19h31_45](https://user-images.githubusercontent.com/38302725/42875222-8c70df6a-8ac6-11e8-8f4f-b8c5631bc63a.png)
