### ISSUE TITLE
Cannot access Gluu Gateway

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#193]
Steps:

1. Start the installation from the dev repo
2. Cancel the installation 12% into `apt install gluu-gateway'
3. Run the command again
4. Run the setup, but don't accept the MIT license first
5. Run the setup again and accept the MIT license
6. Choose to skip the oxd setup
7. Enter the values in the oxd config files manually and save them
8. Restart GG

Expected: It's possible to log in to GG.
Actual: It's impossible to log in to GG. 

Could you look at the logs and check if it's due to misconfiguration?

![2018-07-18_15h31_41](https://user-images.githubusercontent.com/38302725/42863492-c2ba0b7a-8aa6-11e8-96d3-3e56920ff1fd.png)
[oxd_config.zip](https://github.com/GluuFederation/gluu-gateway/files/2204634/oxd_config.zip)
[GG_setup.zip](https://github.com/GluuFederation/gluu-gateway/files/2204638/GG_setup.zip)
[oxd-server.log.zip](https://github.com/GluuFederation/gluu-gateway/files/2204646/oxd-server.log.zip)

**Comment by ldeveloperl1985** [comment]
you did the wrong step. First, do step 7 and then step 6. If you skip oxd setup, there must be a good config oxd server.

**Comment by natt-tester** [comment]
Ok, I run the setup again with the already configured values and it works :)
