### ISSUE TITLE
Integrate test suite

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#205]
Integrate test suite. Microframework for testing Kong plugin using docker-ce with mock oxd-server.
https://github.com/altexy/docker-kong-oxd-server-tests

**Comment by altexy** [comment]
By this commit https://github.com/GluuFederation/gluu-gateway/commit/b08885944a4e406fae03e425327e6f9c6940774b we integrated test suite,
