### ISSUE TITLE
Update GG UI to remove oxd billing note

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#207]
Requirement:
```
we’re making oxd free while we gather more data about usage
so we can remove the pricing note from gg until we have a more solid pricing model
```

Implementation:
Step 1. Remove note from GG UI. 
Step 2. Build the new package.

**Comment by ldeveloperl1985** [comment]
@nikdavnik @adrian-gluu I've update the UI. Now please make GG 3.1.3.1 build

**Comment by nikdavnik** [comment]
new 3.1.3.1 package is ready. its in trusty-devel repo

**Comment by natt-tester** [comment]
Agreed, it's done:
![2018-08-07_16h57_55](https://user-images.githubusercontent.com/38302725/43759605-110dd93e-9a63-11e8-87d7-8a6e6bf3f862.png)
