### ISSUE TITLE
GG dependencies installation should be offline

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#208]
Need update installer to extract pre-build tar.gz with GG node modules into `/opt/gluu-gateway/konga/node_modules` and bower component into `/opt/gluu-gateway/konga/assets/bower_components` and replace [npm install](https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.4/setup/setup-gluu-gateway.py#L393) command in installer.

This files we will add to deb in 3.1.4: `/opt/gluu-gateway/dist/gg_node_modules.tar.gz` and `/opt/gluu-gateway/dist/gg_bower_components.tar.gz`.

**Comment by ldeveloperl1985** [comment]
@nikdavnik  @adrian-gluu add given archive in build and make a new GG 3.1.4
1. https://github.com/ldeveloperl1985/gluu/raw/master/gg_node_modules.tar.gz --> add it in `/opt/gluu-gateway/dist/gg_node_modules.tar.gz`
2. https://github.com/ldeveloperl1985/gluu/raw/master/gg_bower_components.tar.gz --> add it in `/opt/gluu-gateway/dist/gg_bower_components.tar.gz`

**Comment by nikdavnik** [comment]
packages are ready
https://github.com/GluuFederation/gluu-gateway/wiki/Gluu-Gateway-Builds
