### ISSUE TITLE
Luarocks libraries installation should be offline

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#209]
We need to install lua support libraries offline. 
1. json-lua
2. oxd-web-lua
3. json-logic-lua

Also need to replace `luarocks install` command. https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.4/setup/setup-gluu-gateway.py#L367

**Comment by ldeveloperl1985** [comment]
@nikdavnik @adrian-gluu please add [third-party](https://github.com/GluuFederation/gluu-gateway/tree/version_3.1.4/third-party) in GG build at path `/opt/gluu-gateway`. This folder contains git submodules so you need use --recursive git command and make new build.

Below following step to clone with submodule
1. git clone git@github.com:GluuFederation/gluu-gateway.git
2. git checkout version_3.1.4
3. git submodule update --init --recursive

**Comment by nikdavnik** [comment]
packages are ready.
https://github.com/GluuFederation/gluu-gateway/wiki/Gluu-Gateway-Builds

**Comment by ldeveloperl1985** [comment]
@nikdavnik It installs old oxd 3.1.3.1. Please make GG build with oxd 3.1.4. Also I fixed one issue in setup script. Take update and make a new build. Please take care about oxd-http(oxd 3.1.4) init script.

**Comment by nikdavnik** [comment]
gg 3.1.4 packages with oxd 3.1.4 are ready.
