### ISSUE TITLE
Bug : avoid race condition during concurrent handling of users

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/gluu-gateway#22]
During `get_token_by_code` call we overwrite configuration object each time. It perfectly works with one single user, but if there are many users then we will get race condition in this place, for example:
1. user1 - code1
2. user2 - code2
With global configuration overwrite user2 can get code1 due to race condition. Please pass parameters by reference or otherwise use own wrapper instead of global configuration object.

https://github.com/GluuFederation/gluu-gateway/blob/cda9dfc3914095c40f9f23d98e235869829f6bb5/kong-openid-rp/kong/plugins/kong-openid-rp/helper.lua#L35-36

**Comment by altexy** [comment]
@yuriyz @ldeveloperl1985 
This code doesn't exist anymore, I close the issue.
