### ISSUE TITLE
Add UMA support to OAuth2 consumer and upstream plugin

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#24]
Consider the diagram below

![image](https://user-images.githubusercontent.com/3717101/37189352-807c43ee-2319-11e8-9dd8-5c45412a0335.png)

Sequence Diagrams:

* [OAuth Plugin Access Phase](https://github.com/GluuFederation/gluu-gateway/blob/master/doc/sequence_diagram-oauth-consumer)
* [UMA RS Plugin Access Phase](https://raw.githubusercontent.com/GluuFederation/gluu-gateway/master/doc/sequence_diagram_uma_rs)
* [OAuth Plugin Config](https://raw.githubusercontent.com/GluuFederation/gluu-gateway/master/doc/sequence_diagram-config)

Notes: 
* Client must explicity specify whether it is OAuth, UMA or Mix mode.
* In Mix Mode there is no support for claims gathering--`need_info` response is suppressed.
* In Mix Mode, UMA RS Plugin tries to obtain RPT for client and caches it
* In Mix Mode, OAuth Client plugin checks for an associated RPT token, and if present  replaces the OAuth token with the RPT token.

**Comment by yuriyz** [comment]
It would be nice to have tooltip/hint text that explain details of each options. So end-user can clearly understand what each option mean just to avoid any confusion.

**Comment by ldeveloperl1985** [comment]
Completed plugin with UI and tested in the new build. All modes working
Test cases Wiki: https://github.com/GluuFederation/gluu-gateway/wiki/Testing
