### ISSUE TITLE
Question: can user have both UMA and OAuth active at the same time for a given API?

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#245]
![cc](https://user-images.githubusercontent.com/2329776/47636239-a591f080-db7d-11e8-9870-ccdf9084fd01.png)

> Mike: It should be OAuth or UMA
PEP makes no sense there
As I understood it, there are two plugins
the oauth plugin handles client auth–both uma and oauth
the PEP handles making sure the request has the right scopes (either uma or oauth).
Is this incorrect?
Also, you can have both UMA and OAuth active at the same time for a given API?
I created UMA security on /posts and OAuth security on /posts
and it was ok.

**Comment by ldeveloperl1985** [comment]
User cannot configure both plugin at same time. I'll add `or` between this two button.

I'll change the `PEP` to `UMA` but you understood plugin incorrect. Please check sequence diagram if you have any confusion: 

1. **gluu-client-auth**: **introspect OAuth token and check OAuth scope**
Sequence: https://github.com/GluuFederation/gluu-gateway/blob/version_4.0.0/doc/sequence_diagram-oauth-runtime-access-flow

2. **gluu-pep**: **introspect RPT token and check UMA scope(oxd: uma-rs-check-access)**
Sequence: https://github.com/GluuFederation/gluu-gateway/blob/version_4.0.0/doc/sequence_diagram_uma_rs_runtime_access_flow

**Comment by altexy** [comment]
`gluu-client-auth` is OAuth2 cleint authorization and optionally scope-based access control.

`gluu-pep` is UMA PEP only.
I voted for `gluu-uma` name here some time ago.

**Comment by altexy** [comment]
Just for reference:
 - we will add client auth. functionality for UMA plugin.
- names will be changed to `gluu-auth-pep` and `gluu-uma-pep`.

Obviously it doesn't make sense to configure both plugins for one entity.
