### ISSUE TITLE
Add stop to /etc/init.d/gluu-gateway

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#25]
We should have a `stop` command for `/etc/init.d/gluu-gateway`

![image](https://user-images.githubusercontent.com/3717101/35593776-7dd168c8-05d6-11e8-95f9-6c356f2b21db.png)

**Comment by ganesh-at-wiw** [comment]
@Mike, we've intentionally skipped stop. We had a discussion with you as well.
Say someone stops gluu-gateway, but on postgresql, oxd-server are in use for other apps as well, that can cause those apps to misbehave as well.

Still, if you wish, I can incorporate **stop** command.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/gluu-gateway/commit/403ac3e734509b9d9fd1133854586fa78a378854#diff-b9771cd944f206e3107a6b4cfe2dc32d
