### ISSUE TITLE
Kong plugin error handling

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#262]
Imagine that GG plugin encounters any internal error (unexpected response from oxd for example).
The path is unprotected and `anonymous` is set to correct consumer id. So anonymous access to this particular resource is possible.

We have two possible choices:
- respond with 500 or 502, log error
- grant anonymous access, log error

@nynymike what would be a better way?

If anonymous access to resource is not allowed we respond with 401 when error is occurred on authentication phase and with 403 on authorization phase.

**Comment by altexy** [comment]
I have updated the issue, please review.

**Comment by altexy** [comment]
we have two kinds of errors:
1. token provided but authentication fail - we allow access to unprotected paths at the moment. 
2. unexpected errors, like invalid response from oxd - we  log the error and respond with 502 Bag gateway

IMO `grantAccessToUnprotectedResourceOnError` flag should be involved only for first use case.
@nynymike what do you think?

**Comment by nynymike** [comment]
agreed.

**Comment by altexy** [comment]
from chat: 
> Michael Schwartz @nynymike admin gluu 1:59 PM
> yes, agreed

> unprotected paths, it’s better to allow
> maybe we don’t even need the flag.
> I don’t see the security risk
> and if we log it… it’s enough

So, current approach is OK.
