### ISSUE TITLE
Add JWT access token support in Gluu-oauth-pep plugin

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#265]
Add support for JWT access token. User can change its mode to introspect access token so It should be configurable.

**Comment by ldeveloperl1985** [comment]
Agreed

**Comment by altexy** [comment]
@ldeveloperl1985  Where I can find any docs about claims (payload) of JWT created by GS?

**Comment by ldeveloperl1985** [comment]
@altexy here https://gluu.org/docs/ce/3.1.4/admin-guide/openid-connect/#access-token

**Comment by altexy** [comment]
thanks
