### ISSUE TITLE
Add X-Authenticated-Scope in upstream header

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#267]
We missed to add `X-Authenticated-Scope` in upstream header. Please Add it in OAUTH-PEP case.

https://github.com/GluuFederation/docs-gg-prod/blob/4.0.beta/4.0.beta/source/plugin/gluu-oauth-pep.md#upstream-headers

**Comment by altexy** [comment]
Alexander Altshuler @altshuler gluu 2:29 PM
what is the format for multiple scopes?
 
Meghna Joshi @meg gluu 2:30 PM
introspect return array of scope so just return with comma scope

Alexander Altshuler @altshuler gluu 2:30 PM
ok, comma separated list
