### ISSUE TITLE
Add unsupported JWT signing algorithms

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#273]
> Alexander Altshuler altshuler gluu 12:42 PM   
> 
> Hi Yuriy, lua-resty-jwt supports only RS256 and RS512 alg, I see RS384 alg key in jwks response
> Can we limit GS to issue JWT with only supported alg?
> 
> Yuriy Zabrovarnyy YuriyZ admin gluu 1:54 PM
> Hi Alex, not sure, I think it possible to customizeif manually remove unsupoorted algotihm from config but probably better if we can support all that we have in GS. Maybe you can branch this lib and add support.
> one thing to note for future is to support nested JWT
> it was request from samlink, so I think you may got similar requests in future

@nynymike @yuriyz  @ldeveloperl1985 we need to set a priority and approach for this task.

We have a use case then a proper JWT signed by GS with RS386 alg is not recognized by GG as valid.

We have next choices for 4.0 release:
- release without RS384 support, GS must be configured accordingly (not sure is it trivial or not)
- add RS386 support to upstream https://github.com/cdbattags/lua-resty-jwt repo.

I will check how much efforts second approach will take.

**Comment by ldeveloperl1985** [comment]
There are other  **ES384, ES512, ES256** alg also. so should we add support for all Gluu supported algorithm?

**Comment by nynymike** [comment]
That would be nice.

**Comment by altexy** [comment]
@nynymike 
> That would be nice.

I have experimental code with RS384 support.

While implementing RS384 support I have found some critical issues in https://github.com/cdbattags/lua-resty-jwt, possible race conditions is most important one.

These critical issues must be fixed before we will release 4.0 and we may do it relatively fast.
We may suggest our fixes in upstream repo, but it will take some time and efforts.
The simplest way is to use our fork for a while.

Adding ESxxx algorithms will be much more difficult, shall we plan it for 4.0 release?
I don't have ant ETA at the moment, it will require some research.

**Comment by altexy** [comment]
The status of ESxxx algorithms support:

Kong 0.14 is compiled and tested with OpenSSL 1.0.2
OpenSSL 1.1 is required to support ESxxx algorithms.

Upcoming Kong 1.0.0 version will support OpenSSL 1.1.1

We have next choices:
1. Release GG with Kong 0.14. Support only RSxxx signed JWTs. Appropriate `access_token_signing_alg` value should be used. The best would be to have default value containing only RSxxx.

2. Release GG with Kong 1.0. We may support also ESxxx algorithms.
