### ISSUE TITLE
Restore to factory default script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#28]
As Kong loads config data to the database, there needs to be a way to "clear" the data. It could be just a command line script that drops database and re-adds it.

**Comment by ldeveloperl1985** [comment]
@nynymike  There is four kong command to restore kong.
https://github.com/GluuFederation/gluu-gateway#restore-kong-to-factory-default
So it is ok or still, I need to make a new script?

**Comment by nynymike** [comment]
What does this do? There is no explanation on the page.
```
# kong migrations reset
```

**Comment by ldeveloperl1985** [comment]
I've updated details. Please check
