### ISSUE TITLE
Support for multiple AS

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#289]
It is possible that a GG instance could have API's that are protected by different AS's. It would be interesting if there was a way to register multiple AS's, and then to specify for a given API, which AS to use.

**Comment by altexy** [comment]
It is possible with the current design.
We may use one oxd and multiple OPs.
We may use oxd-per-OP approach. It is more scalable.

But IMO we cannot use multiple oxd per one OP.
And this may be a problem for example for Kong cluster.

**Comment by ldeveloperl1985** [comment]
Yes, it is possible. I need to work at GUI side to configure AS in plugin configuration.

**Comment by yuriyz** [comment]
It should be possible to use multiple oxd per one OP. In this case oxd storage has to be redis cluster.

**Comment by mbaser** [comment]
I tested latest version with two OPs.
c1 and c3 are my OPs
I installed GG on c2.
My routes are protected as:
none-claim-gathering by c1.gluu.org
claim-gathering by c3.gluu.org

So, GG can work with multiple OP, even it can work with multiple OXD
