### ISSUE TITLE
UI Bug: Add certificate failed

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#291]
```
sahil: Not able to add certificate key/values,UI crashes and requires restart
```

![screenshot](https://user-images.githubusercontent.com/2329776/52039118-ae69d800-2559-11e9-9f7d-9b3c0b27e474.png)

**Comment by ldeveloperl1985** [comment]
Done. @mbaser test it  I changed the UI as per original konga and kong API. 
![screenshot](https://user-images.githubusercontent.com/2329776/52045685-0c52eb80-256b-11e9-9b1a-07697358632c.png)

**Comment by mbaser** [comment]
I latest build, I can upload certificates. We can close this issue.
