### ISSUE TITLE
API Version in Headers

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#310]
I was talking to a customer, and they pointed out that in some cases the URL may be the same, but the version of the API may be passed as a header parameter. In this case, we may want to configure different OAuth/UMA scopes. I think we should implement this feature in both the backend and GUI.

**Comment by altexy** [comment]
OK, @nynymike  I will research this topic asap

**Comment by altexy** [comment]
https://github.com/Kong/kong/issues/505#issuecomment-362666313

**Comment by altexy** [comment]
I don't think it is a good idea to add such layer into our plugins.
By Kong philosophy `different OAuth/UMA scopes` means the different plugin configurations.
So we need to be able to configure our plugin for the same hosts/methods/paths, but also by request header.

**Comment by altexy** [comment]
@nynymike 
It may be a time-consuming project to add such a feature into upstream Kong.
We will need to follow all Kong rules, write tests.
I see a lot of complaints about the difficulty to reproduce Kong development environment.

At the moment we have next answer:

When Kong will support Route per arbitrary request header - we will be able to do it without any changes on plugin side. Maybe will need some GUI work.

**Comment by nynymike** [comment]
Ok. I didn't have it as an immediate requirement. We can keep an eye on it and guage demand.

**Comment by ldeveloperl1985** [comment]
I think kong header filter feature is covered this issue https://docs.konghq.com/1.3.x/proxy/#request-headers-except-host
@altexy  Please check  and confirm

**Comment by altexy** [comment]
> @altexy Please check and confirm

Agree, Kong 1.3 does support header-based routing
