### ISSUE TITLE
Support Swagger Config 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#318]
GG should be able to consume swagger documents and implement automatically configuration.

**Comment by altexy** [comment]
@nynymike  
I don't understand the topic.
Can you elaborate or provide a real-life example or use case?

**Comment by yuriyz** [comment]
I guess idea to let GG consume swagger specification. GG can traverse swagger specification and automatically protect resources that are defined by specification. All required information are already in swagger spec except scopes. To fill this gap I would propose to introduce `protection rules` which should be configurable (best via UI). 
For example:
1. protect all GET operations with `view` scope
2. paths `/resource` protect with `secure` scope.

Than during swagger specification traversing GG can automatically protect all resources with applying these protection rules.

**Comment by nynymike** [comment]
This is a placeholder ticket so I don't forget. I will add more detail later.

**Comment by altexy** [comment]
I see that OpenAPI 3.0 supports detailed Oauth information including scopes required to access endpoints.
https://swagger.io/docs/specification/authentication/
https://swagger.io/docs/specification/authentication/oauth2/

Not sure that Swagger supports this.

**Comment by ldeveloperl1985** [comment]
During Kong 1.3 changelog review, I found one point. I think kong db import feature has covered this issue 
https://github.com/Kong/kong/blob/master/CHANGELOG.md#cli-3
https://docs.konghq.com/1.3.x/cli/#kong-config

@altexy please check and confirm

**Comment by altexy** [comment]
> @altexy please check and confirm

IMO Kong db import is irrelevant to the issue.

**Comment by altexy** [comment]
IMO the main question is authorization, we should know which scopes are required for different endpoints.
I see 2 possible usages:

1. Import the swagger definition file into gluu-oauth-pep plugin config. This should create entries for every endpoints. Then an admin enter required scopes for every endpoints manually.
2. Support OpenAPI 3.0 where scopes may be provided as swagger yml file.

**Comment by nynymike** [comment]
Not going to implement this.
