### ISSUE TITLE
GG does not check acr claim of id_token for existing session

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#330]
I configured to require U2F or OTP

![](https://user-images.githubusercontent.com/3717101/60104935-b6255580-9762-11e9-927d-c33d47f26d84.png)

Then I login to a different site using only password and navigate to the protected folder. I am not prompted for U2F authentication... I'm allowed in only with password.

**Comment by altexy** [comment]
@nynymike 
We pass configured `required_acrs` values to oxd `/get-authorization-url` endpoint in the  `acr_values` parameter.
We need to check does oxd return the properly formed url for this case.

@ldeveloperl1985 can you test this use case on any our server?

**Comment by altexy** [comment]
@ldeveloperl1985 also it may be the format issue, please, make sure that format in `required_acrs` is correct.

**Comment by altexy** [comment]
@nynymike @ldeveloperl1985 at the moment a configured OpenIDConnect plugin may be configured only for one global `required_acrs`.
Should we think of how to require different auth. levels for different paths for the same site?

**Comment by ldeveloperl1985** [comment]
OXD is generating the correct URL. 

```
TRACE  [14:22:16.259] [dw-17 - POST /get-authorization-url] o.g.o.s.RestResource -  Send back 
response: {"authorization_url":"https://ce-dev6.gluu.org/oxauth/restv1/authorize?
response_type=code&client_id=@!19CF.B296.532F.83E2!0001!25C1.E1E4!0008!585D.B0B0.BA5A.053
B&redirect_uri=https://dev1.gluu.org/callback&scope=openid+oxd+email+profile&state=f859em42t4jhagr
f22sjtm6odh&nonce=hmoulrmuo100ps68ubpv8qjioh&acr_values=u2f+otp&custom_response_headers=
%5B%7B%22max_age%22%3A%223600%22%7D%5D"} 
```

I think we may miss some settings in Gluu CE. @yuriyz scripts are enabled in Gluu CE, is there any setting for this?

**Comment by ldeveloperl1985** [comment]
I've just tested with passport-social auth and disable others acrs.

![passport](https://user-images.githubusercontent.com/2329776/60108088-acf9b000-9785-11e9-83f2-ad32b28ca817.png)

Now it is loading the passport login page.
OXD response 
```
TRACE  [14:39:09.271] [dw-17 - POST /get-authorization-url] o.g.o.s.RestResource -  Send back 
response: {"authorization_url":"https://ce-dev6.gluu.org/oxauth/restv1/authorize?
response_type=code&client_id=@!19CF.B296.532F.83E2!0001!25C1.E1E4!0008!585D.B0B0.BA5A.053
B&redirect_uri=https://dev1.gluu.org/callback&scope=openid+oxd+email+profile&state=fovel1e0f08cf32t
cs9uo2hvsr&nonce=jkatg9l41heu9162r74jgt6nis&acr_values=u2f+otp+passport_social&custom_respons
e_headers=%5B%7B%22max_age%22%3A%223600%22%7D%5D"} 
```
![acrs](https://user-images.githubusercontent.com/2329776/60108151-c3a00700-9785-11e9-8310-631ad48e2000.png)

So GG is generating the correct request. Any one please let us know, @yurem @yuriyz @mbaser   how to deal in U2F and OTP case? GG is generating currect request in both case but Gluu CE shows a only basic username/password page in U2F and OTP case.

**Comment by nynymike** [comment]
You need to add `prompt=login` to force re-authn

**Comment by ldeveloperl1985** [comment]
Thank you Mike, after adding `prompt=login` it works. I'll create PR for this.

**Comment by altexy** [comment]
> You need to add prompt=login to force re-authn

@nynymike with `prompt=login` user would be reauthenticated always even it has enough auth. level.

IMO we need to check in the OpenID Connect sessions existing arcs and force reauthentication.

**Comment by altexy** [comment]
After some reading of OpenId Connect spec IMO we should not include `acr_values` because it is requesting of `Voluntary Claim`.
We must request the `Essential Claim` by using the "claims" Request Parameter:
```json
{
    "acr": {
         "essential": true,
         "values": ["val1", "val2"]
    }
}
```

**Comment by nynymike** [comment]
IMHO, you should look at the id_token, look at the `acr` claim, in the id_token, and if it is not sufficent, then use the `prompt=login` param for re-authn.  I don't thin the Gluu Server supports the "essential claim" feature.

**Comment by altexy** [comment]
@nynymike what it the desired semantic if multiple `acr`s are configured?
1. All required
2. Any one
3. Something alse

**Comment by nynymike** [comment]
If multiple acr's are specified, any one is ok. For now, I think the best way is to pick the acr with the lowest numeric level.

**Comment by altexy** [comment]
We may order arcs (low level first) or make an admin possibility to order them.
Otherwise, the order of acrs in UI will have an influence.

**Comment by altexy** [comment]
>Alexander Altshuler 1:31 PM
>would GS reject the auth. request if acr_values contains only script(s) not available for user or not enabled?

>Yuriy Zabrovarnyy 1:36 PM
>it will try to fallback to default one which is set in oxauth configuration. And if it’s not enabled too then it will reject request

So it is possible that we requested an acr, but GS authenticate with default acr.
@nynymike 
What should be the desired GS behavior for this use case? Allow or Deny?

If Deny it requires to maintain a user session state (which acr we requested) otherwise we may have infinity redirect loop.

**Comment by nynymike** [comment]
Let's say GG requires acr's A, B, C...
And Gluu Server offers only acr's  X,Y,Z
Then GG should deny.

**Comment by altexy** [comment]
thanks

**Comment by ldeveloperl1985** [comment]
Done
