### ISSUE TITLE
OIDP plugin failed to handle session expire case

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#333]
After the session expires, OIDC plugin going for multiple time authentication.

How to reproduce:
1. set max_age and max_authn_age to 60 sec
2. open browser windows and request --> successfully logged in here
3. leave a window for two minute
4. request for another other protected path

at step-4, it redirected to OP and get back to kong, multiple times. As per kong logs, it successfully gets the refresh token but then also it going for authentication, after successful authentication, it again goes for authentication until it stops by browser `Too many redirections`.

Please check logs.
1. check kong logs from time `2019/07/08 17:51:05`, you will get idea [error.log](https://github.com/GluuFederation/gluu-gateway/files/3368392/error.log)

2.  [oxd-server.log](https://github.com/GluuFederation/gluu-gateway/files/3368401/oxd-server.log)

3.  [oxauth.log](https://github.com/GluuFederation/gluu-gateway/files/3368404/oxauth.log)

4. Video 
[oidc-plugin.mp4.zip](https://github.com/GluuFederation/gluu-gateway/files/3368407/oidc-plugin.mp4.zip)

**Comment by nynymike** [comment]
`id_token` expiration is not a problem. It must not be expired at the time you create the session. But after that, it's up to the application how long to maintain the application session.

**Comment by altexy** [comment]
Application session is properly managed.

@ldeveloperl1985 can you, please, test this use case with `333_redirect_loop` branch?

**Comment by ldeveloperl1985** [comment]
Sure, I'll test it

**Comment by ldeveloperl1985** [comment]
@altexy I've tested and the problem is solved. After the expired session, it goes for auth again. Also tested refresh token case. It is working well. @altexy please make a PR. I'll merge it.

**Comment by ldeveloperl1985** [comment]
Done
