### ISSUE TITLE
Konga: add checkbox to toggle kong_acts_as_uma_client during OAuth2 Client creation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#34]
![image](https://user-images.githubusercontent.com/3717101/36116497-18823e54-0ffc-11e8-882f-3da485e64435.png)

**Comment by ldeveloperl1985** [comment]
Solved https://github.com/GluuFederation/gluu-gateway/commit/7f83ac2af0bbb17fb63b05703368171daae190ed
