### ISSUE TITLE
OIDC Plugin test case failing

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#341]
`gluu-openid-connect` plugin lua test case failing. It goes for refresh token as well as for silent authentication.

```
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:177 [gluu-openid-connect] access_token refreshed: 88bba7f5-961c-4b71-8053-9ab35f1ad333 updated refresh_token: 33d7988e-6ffb-4fe5-8c2a-0e158691d333
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:321 [gluu-openid-connect] session.present=true, session.data.id_token=true, token_expired=false
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:347 [gluu-openid-connect] Silent authentication is required - Redirecting to OP Authorization endpoint
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] kong-common.lua:69 [gluu-openid-connect] Current datetime: 1564474734.288 access_token.expire: 1564475018.235

```

**Comment by altexy** [comment]
@ldeveloperl1985 can you, please, provide more context about use case?

**Comment by ldeveloperl1985** [comment]
@altexy 
It goes for a refresh token after successful get `get_access_token_by_refresh_token`, it re-set(update) the session but then it going for auth flow again which is wrong. it should not go for auth flow again. 
Please check the `basic` test case https://github.com/GluuFederation/gluu-gateway/blob/version_4.0/t/specs/gluu-openid-connect/test_spec.lua#L177
it is failing here https://github.com/GluuFederation/gluu-gateway/blob/version_4.0/t/specs/gluu-openid-connect/test_spec.lua#L225

**Comment by altexy** [comment]
@ldeveloperl1985 thanks, will figure it out asap

**Comment by ldeveloperl1985** [comment]
Done
