### ISSUE TITLE
URL based Stepped up authentication in OIDC plugin

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#345]
Add feature in the OIDC plugin that enables stepped up authentication based on URL (resource), e.g.: 

1. `site.com/account_info` –> prompt=login acr=basic
2. `site.com/wire_transfer` –> prompt=login acr=super_gluu

**Comment by altexy** [comment]
We may use our wildcard/regexp notation for path matching.

**Comment by altexy** [comment]
We may implement this feature in some days, maybe add it into 4.0 milestone?

**Comment by altexy** [comment]
@ldeveloperl1985 @nynymike @willow9886

**Comment by ldeveloperl1985** [comment]
> We may implement this feature in some days, maybe add it into 4.0 milestone?
> I'm about GG side. @ldeveloperl1985 may give an estimation for Konga.

It will take me around 2-3 days.

**Comment by willow9886** [comment]
Seems reasonable.. I would include it in 4.0 then.

**Comment by ldeveloperl1985** [comment]
@willow9886 do you think we need to add the HttpMethod filter also in this case? @altexy wanted to add HttpMethod also.

For example:
1.`site.com/account_info` `GET` –> prompt=login acr=basic
2. `site.com/wire_transfer` `GET` –> prompt=login acr=super_gluu
3. `site.com/wire_transfer` `POST` –> prompt=login acr=basic
4. `site.com/wire_transfer` `?` –> prompt=login acr=basic

Note: `?` wildcard, allow all the methods

**Comment by willow9886** [comment]
@ldeveloperl1985 yes, definitely.
