### ISSUE TITLE
Unescaped space character in a URI - possible security vulnerabilities

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#347]
Most of the web servers would ignore the URI suffix after unescaped whitespace character.

We use `ngx.var.uri` to obtain the normalized path.
Normalized means that any relative path are resolved and query parameters removed.

But `ngx.var.uri` would return all chars after unescaped space also and our matching code may fail.
In the worst key, we may wrongly provide access to a protected resource.

IMO we need to strip all chars after first unescaped whitespace before URI matching.
It is a quick fix.

Plugins:
- gluu-oauth-pep
- gluu-oauth-uma
- gluu-openid-connect

**Comment by ldeveloperl1985** [comment]
@altexy could you please describe with examples?

**Comment by altexy** [comment]
Suppose we have the protected path `/command1` 
If an attacker issues HTTP request with request line `POST /command1 bla HTTP/1.1` our code doesn't match the request.

I know this is incorrectly formed HTTP request, but it is very simple to reproduce it with curl, for example.

**Comment by altexy** [comment]
Sorry, the code is still not merged
