### ISSUE TITLE
Design GG UI for URL based Stepped up authentication feature in OIDC plugin

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#349]

**Comment by ldeveloperl1985** [comment]
Designed form screenshots, @altexy  please let me know if you wanna change anything
![oidc-full1](https://user-images.githubusercontent.com/2329776/62618994-44c8ed00-b933-11e9-997e-c3b18a64005e.png)

**Comment by altexy** [comment]
"required acrs" is used in the same way as `/??` for path and `/?` for methods.
IMO we should avoid one of them. What can we do:
1. Remove "required arcs" at all. Possibly we may precreate such expression in UI, maybe make it mandatory.

2. Don't allow any path and any methods expression in UI and leave "required acrs" as is.

I would vote for the first approach.
But the current "required arcs" list is also informative - it lists possible acrs and levels.
IMO we still need this info somewhere, maybe use checkboxes in acr expression.

**Comment by ldeveloperl1985** [comment]
> Remove "required arcs" at all. Possibly we may precreate any-path-any-method expression in UI, maybe make it not removable from UI.

Sure, I'll do the first approach 

> maybe use checkboxes in acr expression.

Yes, sure, I'll add checkbox selection in acr expression

**Comment by ldeveloperl1985** [comment]
@altexy you want like in below screenshot, right? please confirm.
![Screenshot (8)](https://user-images.githubusercontent.com/2329776/62780732-fd2d9700-bad3-11e9-83e7-5a39077010af.png)

**Comment by altexy** [comment]
yes, look correct.

At the moment if we select more then one ACR - it means anyone from selected.
We plan to support multiple id_tokens in user session soon.
But the semantic will be the same - anyone from selected, isn't it?

The main purpose for multiple id_tokens in user session is to avoid re-authentication while surfing different paths with different required acrs.

**Comment by nynymike** [comment]
Yes, multiple id_tokens could happen during re-authn. However, it might only be necessary to keep the most current id_token, with the highest authn_level. As long as the authn level is exceeded, we don't need an exact string match on the mechanism.

**Comment by altexy** [comment]
At the moment the acrs levels are displayed only for information purpose.
We may add level-related semantic, but it is a major change and it should be discussed carefully to avoid any misunderstanding.

With the current approach (requiring one of the listed acrs) I will explain the problem we have.
Suppose we require `basic` acr for the whole site.
User opens the site, redirected to OP, authenticate with `basic` method, redirected to the site.
Next, the user trying to open the page which requires `otp` acrs.
User redirected to OP, auth. with OP, redirected to the site.
At this point, id_token contains only `otp` acr.
When the user returns to the homepage, the `basic` acrs is required and the current code would redirect to OP again.
It is not what we want definitely.

I planned to refactor our code and maintain more than one id_tokens on the user session.
It would avoid the unnecessary redirecting to OP.

If we would add acr-level semantic we may avoid supporting multiple id_tokens and keep only one with the highest authn_level.

We should clearly understand that level semantic is very different from the current.
For example, we cannot force a user to authenticate with `otp`  if he already has `u2f`

@ldeveloperl1985 @nynymike @willow9886 

Please, share your thoughts.

**Comment by willow9886** [comment]
@altexy agreed, acr_levels is definitely the preferred approach.

**Comment by ldeveloperl1985** [comment]
@altexy 
What happens when a user registers the path as below? Just in case, user register multiple acr for one of the path
```
/addticket - basic
/payment - otp(level-40), u2f(level-50)
```
As my expectation, when user request for path `/addticket`
1. redirected to op
2. basic auth
3. allow access

when user request for path `/payment`
1. redirect to op
2. u2f auth because u2f auth level is higher and ignores OTP
3. allow access

when the user again requests for path `/addticket`
1. allow access, no auth redirection again

will it work like this or not?
Seems like we need to maintain multiple id token here.

**Comment by altexy** [comment]
@ldeveloperl1985 using acr-levels approach we will not need multiple id_tokens.
GG will need to be aware about acr->level mapping and allow access if user has an acr with higher or the same (?) level.

**But IMO it violates the OpenID Connect spec.** @willow9886 @nynymike 

Maybe we give an admin the choice?
`multiple_id_tokens` - boolean, default `true`
`acr_level_auth` - - boolean, default `false`, possibly imply `multiple_id_tokens = false`

**Comment by ldeveloperl1985** [comment]
```
1. As my expectation, when user request for path /addticket
- redirected to op
- basic auth
- allow access

2. when user request for path /payment
- redirect to op
- u2f auth because u2f auth level is higher and ignores OTP
- allow access

3. when the user again requests for path /addticket
- allow access, no auth redirection again
```

In the third case we need previous id_token acr, right?

**Comment by altexy** [comment]
> - u2f auth because u2f auth level is higher and ignores OTP

GS may use ANY acr at the moment

> In the third case we need previous id_token acr, right?

With the current approach - yes.

**Comment by ldeveloperl1985** [comment]
Ok, my vote is to `acr_levels` approach. the configuration option is also best

**Comment by ldeveloperl1985** [comment]
@altexy Below is the UI to configure acr_expression, please check and let me know if you have any suggestions and change. Updated docs are here https://github.com/GluuFederation/docs-gg-prod/blob/update_oidc/docs/source/plugin/gluu-openid-connect-uma-pep.md#configure-plugin-using-gg-ui 
![oidc4](https://user-images.githubusercontent.com/2329776/63922188-d83c9c00-ca61-11e9-9537-e8e1445e0f93.png)
![oidc5](https://user-images.githubusercontent.com/2329776/63922189-d8d53280-ca61-11e9-8b2e-8a446b258a71.png)
![oidc5-2](https://user-images.githubusercontent.com/2329776/63922190-d8d53280-ca61-11e9-8bf9-b4d38ceabb10.png)

**Comment by ldeveloperl1985** [comment]
Done
