### ISSUE TITLE
Update text UMA-RS API config

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#35]
**Never** hard code a link to a specific docs version. 

![image](https://user-images.githubusercontent.com/3717101/36646634-a72cf1f6-1a3f-11e8-830e-c78bf1345c32.png)

In this case, the text should read. 

```
Protect API paths by requiring specific UMA Scopes for certain methods.
 
```

**Comment by ldeveloperl1985** [comment]
I've fetched oxd version from Konga config and made dynamic docs link. Also change text `The path which you want to protected by UMA` to `Protect API paths by requiring specific UMA Scopes for certain methods.`
![issue35](https://user-images.githubusercontent.com/2329776/36660688-129618ae-1aff-11e8-8d5e-6694b698d67a.png)

**Comment by nynymike** [comment]
Per my original comment "Never hard code a link to a specific docs version..."--it is the text "Register a protected.... " that ends in a link that is the problem text.

**Comment by ldeveloperl1985** [comment]
I've changed text with a dynamic link. Please take look at screenshot
![screenshot](https://user-images.githubusercontent.com/2329776/36730371-32ca7e46-1bed-11e8-873c-03e934b40951.png)

**Comment by nynymike** [comment]
For the third time: "Never hard code a link to a specific docs version..."

**Comment by ldeveloperl1985** [comment]
I've already changed it. This is not hard code. I fetch oxd version from Konga config and set it in the link.
