### ISSUE TITLE
Install and setup ca-certificates for GG 4.0 package

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#351]

**Comment by altexy** [comment]
We need also to add `lua_ssl_trusted_certificate` to kong.conf.

The certificate location may differ between Linux distributions. 

For debian Linuxes:
`lua_ssl_trusted_certificate "/etc/ssl/certs/ca-certificates.crt";`

FIXME: CentOS/RHEL the cert location is different, the CA bundle location may be located at /etc/pki/tls/certs/ca-bundle.crt.

Also, it may be a good idea to increase `lua_ssl_verify_depth` from default 1 to something like 3 or 5.

**Comment by ldeveloperl1985** [comment]
Updated the setup script, kong configuration for
- **Ubuntu16**: `lua_ssl_trusted_certificate = /etc/ssl/certs/ca-certificates.crt`
- **REHL7** and **CENTOS7**: `lua_ssl_trusted_certificate = /etc/ssl/certs/ca-bundle.crt` - @altexy I've tested and it is working, the path for REHL7 and CENTOS7 is `/etc/ssl/certs/ca-bundle.crt`

@altexy  I've setup `lua_ssl_verify_depth = 3` and it is working well.

Now, @nikdavnik your turn to add `ca-certificates` package dependency in GG package and build a new package.

**Comment by ldeveloperl1985** [comment]
Done, Tested new GG Package, OS: Ubuntu 16 and CentOS7
