### ISSUE TITLE
HTTP Calls in setup script not respecting proxies

### ISSUE THREAD

**Issue by ryanwilliamnicholls** [GluuFederation/gluu-gateway#352]
The http calls done during the setup of gluu gateway don't respect any proxies that are set on the machine. This can cause the script to fail if setup behind a corporate proxy.

I was able to fix this behind our corporate proxy by hardcoding the proxies in into the requests.post and requests.get calls in the script, but these should be taken from the systems proxy settings.

**Comment by willow9886** [comment]
OK, thanks for the note. I assume this is version 4.0 beta? We'll take a look. 

BTW, which customer account is this associated with? We typically prefer to see customer issues opened via the [Gluu Support portal](https://support.gluu.org) so we can gather appropriate details about the environment for troubleshooting. 

Thanks.

**Comment by altexy** [comment]
@ldeveloperl1985 our plugins Lua code also should be modified in order to support http/https proxies.
I may take care of this part. Possibly by separate ticket.

**Comment by ldeveloperl1985** [comment]
@altexy I don't have experience with corporate proxy things. could you please share some details what you will do with Lua code so that I'll get the idea to deal with GET|POST request in python script in the corporate proxy case

**Comment by altexy** [comment]
Kong ships with https://github.com/pintsized/lua-resty-http included (version 0.12 I think).
It has support for HTTP/HTTPS proxies. We just need to set appropriate config options.
https://github.com/ledgetech/lua-resty-http#set_proxy_options

https://justintung.com/2013/04/25/how-to-configure-proxy-settings-in-linux/
Above is the first result from Google ;-)
As you can see there is no one standard single point of HTTP Proxy settings on Linux box.
It depends on the Linux flavor and application.

**Comment by altexy** [comment]
There are some aspects of the problem:
1. Ability to get proxy setting of current Linux box. 
But, IMO, the ability to manually specify such settings may be enough.

2. How to do it technically in Lua, NodeJS, whatever we use.
I may do in Lua code, NodeJS should have similar setting, etc.

**Comment by ldeveloperl1985** [comment]
> Proxy settings should be used for communications to the Interner, local communications between local services should be direct.


@altexy  Yes, it should be for the Internet but as @ryanwilliamnicholls mention above
> hardcoding the proxies in into the requests.post and requests.get calls in the script

Currently, Python script calling two things 
1. Kong API for metrics config (all GET calls are to Kong API)
2. Gluu Customer Registration endpoint (POST calls)

so why @ryanwilliamnicholls is facing this problem even if it is in local(GET Calls). @ryanwilliamnicholls could you please tell us where you get this problem in `Kong API` or `gluu registration endpoint`, also can you share about your proxy structure and python script fix.

**Comment by ryanwilliamnicholls** [comment]
In my case, the main issue was when the setup python script tried to make post calls to the gluu customer registration endpoint. I fixed the issue by adding a hard coded dictionary of my proxy addresses to the requests.post call in the script, e.g:
```
proxies = {'http': 'http://localhost:3128', 'https': 'http://localhost:3128'}
response = requests.post(endpoint, proxies=proxies, ect.....
```

I added the proxies to the get calls as well as they weren't hitting the proxy and i was unsure at the time if the script made any external GET calls, but having another look at what the script is doing it should be fine as they were all localhost.

For context i'm running on ubuntu 16.04 with a cntlm proxy running on the local machine. The proxy upstreams requests to my corporate proxy with my details. It has exemptions for localhost and a few internal domains, so it wouldn't have been effecting the GET calls.

Also, my bad for opening this here instead of on the customer support portal, i was doing a trial evaluation to determine if our company wanted to use the product, and hadn't created an account/was unaware of the support portal. 
I can close this issue and remake it on the support portal if that's preferred.

**Comment by ldeveloperl1985** [comment]
@ryanwilliamnicholls  Yes, please opening issue in support portal and add this issue reference and thank you for providing information. we will discuss more on the support portal if any need occurs.

**Comment by ldeveloperl1985** [comment]
our Python script is using the `request` python module and this module by default respecting the proxies. @ryanwilliamnicholls  you just need to export or set `HTTP_PROXY` and `HTTPS_PROXY` env vars. we tested and it is working.

**Comment by ryanwilliamnicholls** [comment]
I had both those environment variables set and it didn't pick it up, weird. Might be some quirk of the module.

**Comment by ldeveloperl1985** [comment]
Check python docs here https://2.python-requests.org/en/master/user/advanced/#proxies

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('http://example.org')
```

**Comment by ryanwilliamnicholls** [comment]
The issue was the scripts didn't have permissions to write to their log files when run as the default user, so i ran them using sudo. The proxy variables weren't set when running through sudo.
