### ISSUE TITLE
Modify API Security

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#36]
As far as I can tell, there is no way to get back previous security setting or to change the configuration.  This will not work--being able to view and change the security is essential.

**Comment by ldeveloperl1985** [comment]
I've only updated the Konga design for edit mode but on plugin side work is in pending. Because In oxd there is no command for update and yuriy going to add this feature in oxd 3.1.3 https://github.com/GluuFederation/oxd/issues/167
