### ISSUE TITLE
GG Lua deps and plugins archive

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#365]
Stock github release doesn't includes submodules, we decided to create a script which:
1. get current folder (to be current folder agnostic)
2. cd to root git repo folder
3. update all submodules
4. copy all required Lua files into an archive, need folder/filename convention
5. git commit the archive

**Comment by altexy** [comment]
Hi @ldeveloperl1985 

Some ideas for future enhancement:
1. Copy only Lua files to the archive (for Lua deps particular, `third-patry`)
2. Create makefile for conditionally build, will need to specify all files we depend.
Interesting task - depend from git submodules. Makefile should be able to detect submodules changes.

**Comment by ldeveloperl1985** [comment]
Ok, changed the milestone 4.0 to 4.0

**Comment by ldeveloperl1985** [comment]
Done
