### ISSUE TITLE
GG cluster setup

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#367]
Make one zip which has all our plugins, third-party libs, and one setup script so to setup kong cluster setup like below
1. User will install kong from official kong website
2. They need to download our zip, it will have our plugins, third-party libs, and kong-setup.py
3. extract the zip
4. run the `gg-kong-setup.py` :- this script will ask the DB host and password, configure the kong.conf, install plugins in a kong and star kong.
5. Update docs

**Comment by ldeveloperl1985** [comment]
Done
Docs updated please check https://gluu.org/docs/gg/clustering/

**Comment by altexy** [comment]
The cluster docs should be proof read, I see some issues here.
@ldeveloperl1985 How I can push my suggestions?

**Comment by ldeveloperl1985** [comment]
@altexy  Please clone repo https://github.com/GluuFederation/docs-gg-prod/tree/4.0 and push your fixes

**Comment by ldeveloperl1985** [comment]
All the content in `source` folder here https://github.com/GluuFederation/docs-gg-prod/tree/4.0/docs/source. it is mkdocs. you can install it https://www.mkdocs.org/#installation and run on local so that you can see UI in your local machine.
```
1. install mkdocs
2. clone repo
3. cd docs-gg-prod/docs
4. use this command `mkdocs serve --dev-addr=127.0.0.1:4333` to run in local
```
