### ISSUE TITLE
OpenID plugin configuration for UMA access control:  Push UserInfo token

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#370]
We need to send the Gluu Server more information in order to make useful policies in the Gluu Server.

1. It should be possible to push the Userinfo JWT too, because that has the user claims. The `id_token` doesn't have the user claims (just the authentication event details).  
2. We should send the HTTP request object because it has info like what kind of browser it is, and the original remote ip address
3. Allow the admin to set static claims. For example, {'adminFeature': 'true', 'version':'1.4'}.   

The pushed claim token should create a new JSON and encode it like this:  
```
{
  `id_token`:  {decoded id_token},
  `userinfo`:   {decoded userinfo token},
  `request_object`:  {headers as json},
  `static`: {}
}

```

**Comment by altexy** [comment]
@nynymike 
Here is API link https://gluu.org/docs/oxd/4.0/api/#operations-developers-uma-rp-get-rpt
By `/uma-rp-get-rpt` oxd endpoint we may push claim token.

As I know at the moment GS support only  one  `claim_token_format` : `http://openid.net/specs/openid-connect-core-1_0.html#IDToken`

Would it require some changes on GS side also?

**Comment by nynymike** [comment]
The Gluu Server doesn't care what is the claim token format. That's informational for the policy.

**Comment by altexy** [comment]
@ldeveloperl1985 tested that it is possible to pass any JWT with None alg as pushed claims while getting RPT.

I offer to use Lua based configuration approach similar to our custom header, but with some specific.

My first design was as below:
we define some records, every record has `name` and `value_lua_exp`

But after some reflection, I offer one single `pushed_claims_lua_exp`.
We may populate environment with use id_token, userino.
we may expose [kong.request](https://docs.konghq.com/1.4.x/pdk/kong.request/) to get access to request object.

With the latest approach, we may push id_token (as now) by just specifying `id_token` in `pushed_claims_lua_exp`.

Mikes example may look as below:
``` Lua
{
  id_token = id_token,
  userifo = userinfo,
  headers = request.get_headers(),
  string_static_claim = "bla-bla",
  number_static_claim = 123,
  boolean_static_claim = true,
}
```

**Comment by altexy** [comment]
@ldeveloperl1985 I'm implementing this issue, hope it will be ready on Monday
