### ISSUE TITLE
Map Userinfo and id_token claims to HTTP headers

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#373]
GG admins should be able to map distinct HTTP headers to claims in the id_token and Userinfo JWT.  The admin should be able to set the name of the HTTP header.  The value of the header should be string if it's single value, and a JSON array if it's multi-value.  If no claim is present in the token, omit the header.  

This feature is needed to maintain behavior with legacy WAM platforms.

**Comment by altexy** [comment]
Here is original Mike's wireframe:
https://raw.githubusercontent.com/GluuFederation/gluu-gateway/master/kong-openid-rp/doc/konga-openid-wireframe.png

@nynymike 
Should we map ALL claims in a token (id_token, userinfo) to a distinct header?
Or customer should be able to specify claims of interest?

**Comment by nynymike** [comment]
Yes it would simplest to iterate through the claims. It would also be nice if you could provide a way to do a claims mapping. In the mapping, I think using `HTTP_KONG_` ia a mistake. If a legacy application is expecting `HTTP_SM_uid` if we can provide the same header, the app need not be upgraded. So perhaps we could also provide a tool where additional claims could be added. For example, map the `given_name` claim to `HTTP_SM_givenName` (in this case you can leave both headers.

**Comment by altexy** [comment]
Proposed schema:
```
                    {
                        custom_headers = {
                            required = false,
                            type = "array",
                            elements = {
                                type = "record",
                                fields = {
                                    { header_name = { required = true, type = "string" } },
                                    { value = { required = true, type = "string" } },
                                    { format = { required = false, type = "string" } }, -- TODO should be an enum JWT, base64, urlencoded, list
                                    { sep = { required = false, type = "string" }
                                    { iterate = { required = false, type = "boolean"} }
                                },
                            },
                        }
                    }
                },
```

`header_name` - self-documented, may contain embedded placeholder when we iterate thru claims, take a look at `iterate` field below
`value` - the Lua expression, define the value in the environment, for example `userinfo.email`
For OpenID Connect use case the environment is populated with 2 root values `id_token` and `user_info`.
`format` - the format used to encode the value. Different types of values have different default formats:
- object - base64
- scalar value - urlencoded
- array of scalars - urlencoded values with separator
The possible formats:
- urlencoded
- base64
- JWT (with none alg)
- list with separator

`sep` - make sense only for `list` format, default values is `,`.
`iterate` - the `value` should point to an object, for example `id_token`
We will iterate thru keys/values and create separate header for every key. The captured key is accessible in `header_name` via special placeholder, for example {*}.

Below is example JSON:
```
{
  "custom_headers" : [
    { "header_name" : "HTTP_SM_givenName ", "value" : "userinfo.given_name" },
    { "header_name" : "KONG_IDTOKEN_JWT", "value" : "id_token", "format" : "JWT" },
    { "header_name" : "KONG_CUSTON_ARRAY_CLAIM", "value" : "userinfo.array", "format" : "list", "sep" : "; " },
    { "header_name" : "KONG_OPENIDC_USERINFO_{*}", "value" : "userinfo" }
  ]
}
```

Current implementation is hardcoded to set 2 headers:
``` Lua
    local new_headers = {
        ["X-OpenId-Connect-idtoken"] = encode_base64(cjson.encode(id_token)),
        ["X-OpenId-Connect-userinfo"] = encode_base64(cjson.encode(session_data.userinfo))
    }
```

We may provide some defaults in UI for things like above, but an admin will be able to fully customize headers set.

IMO we may use this microframework not only for OpenID Connect plugin, but everywhere we need to set any headers, of course the environment would be different.

**Comment by ldeveloperl1985** [comment]
Ok, so admin should have to use `userinfo` and `id_token` during configurations for populating the values, right?

**Comment by altexy** [comment]
> Ok, so admin should have to use `userinfo` and `id_token` during configurations for populating the values, right?

No, we will document, which values are set in the environment.
As I wrote, for gluu-openid-connect plugin the environment will consist of 2 root objects `id_token` and `userinfo`.
Our plugin will use the config and the environment to form the headers.

**Comment by ldeveloperl1985** [comment]
@nynymike can we map **access_token** into **HTTP Headers**? Just a question in my mind bit not sure whether it is a useful enhancement or not.

**Comment by nynymike** [comment]
It would be nice if we can send the access token, but it should be off by default.

**Comment by ldeveloperl1985** [comment]
Ok, Created another issue for it https://github.com/GluuFederation/gluu-gateway/issues/382
