### ISSUE TITLE
Improve UMA RS scope expression UI

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#38]
![image](https://user-images.githubusercontent.com/3717101/36684236-5657403c-1ae5-11e8-92ed-9abfd4601aa0.png)

The source for the scope expression should be hidden. If the user explicitly request to see it, it should be expose a pop-up text area (not one long line).

There should be a link to the "SECURITY" view of the API, which should display graphically the existing scope expression.

**Comment by ldeveloperl1985** [comment]
Already completed in this commit https://github.com/GluuFederation/gluu-gateway/commit/90b2c9f3c7117db97ec041a221ea64fc10a1a534
