### ISSUE TITLE
gluu-metrics gluu_prometheus_server_host DNS resolution and architectural issues

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#384]
gluu-metrics plugins periodically resolve `gluu_prometheus_server_host` and update `ip_restrict_plugin_id` configuration.

It may be an issue for declarative db-less Kong deployment, because we need to update the whole node config for db-less case.

Also, it is not clear for me how we test this procedure in our test suite.

Are there any docs about how gluu-metrics plugin should interact with Prometheus server?

Because gluu-metrics plugins play important role it looks like a blocker for db-less declarative deployment.

**Comment by ldeveloperl1985** [comment]
here is the docs for gluu-metrics plugin configurations, parameters details, and setup with Prometheus server

**Comment by altexy** [comment]
IMO we should make 
`ip_restrict_plugin_id`, `gluu_prometheus_server_host` parameters of `gluu-metrics` plugin optional.
And don't do any DNS resolution, ip_restriction reconfiguration if they are not provided.

It allows an admin to configure gluu-metrics in db-less mode.
But access to the metrics endpoints from outside world still needs to be opened by others means.

**Comment by altexy** [comment]
Alexander Altshuler gluu staff 17:20
For cluster use case the problem is more complicated:
usually nodes added/removed from a cluster as needed
it is dynamic process
it would be very difficult, or even impossible to configure prometheus server to get all metrics from a cluster’s nodes


nynymike Michael Schwartz admin owner gluu staff 22:34
**ok, then the solution needs to be re-evaluated.
I would say remove it for now.**

ip restriction plugin parameters/behavior has been removed as incompatible with declarative Kong config.
