### ISSUE TITLE
Migrate Konga part to gluu-gateway-ui repository

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#389]
We need to move the history of `master` and `version_4.1` branches to new repo.

IMO we need to test the proposed sequence below on a test git repo:
```
# in current gluu-gateway git repo local copy (master and version_4.1 branches up-to-date)
git remote add ui git@github.com:GluuFederation/gluu-gateway-ui.git
git push ui master
git push ui version_4.1
```
IMO we don't need to migrate tags.

After successful migration we should remove unnecessary files from both repos.
Then the issue may be closed.

**Comment by altexy** [comment]
@ldeveloperl1985 I have moved `master` and `version_4.1` branches to new git repo.

Is all you need for UI part is within `Konga` folder?
If yes, does it make sense to remove single top level `Konga` folder?

Can you start working on this repo from the moment?
I want to remove Konga part from GG repo asap.

**Comment by ldeveloperl1985** [comment]
@altexy 
>Is all you need for UI part is within Konga folder?
If yes, does it make sense to remove single top level Konga folder?

Yes, all the thing is in the Konga folder. Yes, remove it.

>Can you start working on this repo from the moment?
I want to remove Konga part from GG repo asap.

Yes you can remove Konga from `gluu-gateway` repo
