### ISSUE TITLE
Konga: Allow admin to specify UMA client

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#39]
![image](https://user-images.githubusercontent.com/3717101/36767071-81668e80-1bfe-11e8-90ee-f9e55058593f.png)

If the client is sending UMA access tokens, it would improve security if the admin has to specifically allows this.

**Comment by ldeveloperl1985** [comment]
Related to https://github.com/GluuFederation/gluu-gateway/issues/44
