### ISSUE TITLE
Farther GG repo decomposition

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#393]
@ldeveloperl1985 we need to discuss the subj.

IMO, the next components are a logically separate components:
- `setup`/`debian`/`rpmbuild`
- `gg_demo`
- `gluu_flask_demo`
- `license-registration` (is it actual?)

For every component above we need the decisions:
1. Actual?
2. Move to separate git repo?
3. Save git history? (forking the whole repo is expensive)
4. Require fixes while moving to separate repo, for example for OS packages?

IMO `deprecated` and `postman` folder should be removed, if needed we may get it from history

`docs` - content must be revised, obsolete, not actuals files - removed

I would be happy if eventually, we will have the structure like below:
```
lib/*
t/*
docs/*
```

Take a look at almost all OpenResty libraries - you will see a similar structure.

**Comment by ldeveloperl1985** [comment]
@altexy 

----------------------------------------------------------------------

let's move below folders in **gluu-gateway-setup** repo and remove from **gluu-gateway** repo.
```
setup/debian/rpmbuild
gg_demo
gluu_flask_demo
license-registration (is it actual? --> Yes)
```

-----------------------------------------------------------------

> IMO deprecated and postman folder should be removed, if needed we may get it from history

Yes lets' remove these folders


---------------------------------------------------------------------

> docs - content must be revised, obsolete, not actuals files - removed

I think nothing is important, we have separate gg docs for docs so we can remove everything inside this docs folder


------------------------------------------------------------------
> I would be happy if eventually, we will have the structure like below:

Yes agreed
