### ISSUE TITLE
Print Gluu Support License on setup

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#4]
We should print the [Gluu Support](https://raw.githubusercontent.com/GluuFederation/gluu-gateway/master/LICENSE) license and ask the user:

```
Do you acknowledge that use of the Gluu Gateway is under the GLUU-SUPPORT license? [y|N]: 
```

Defaults to not accepting the license.

**Comment by ldeveloperl1985** [comment]
Done https://github.com/GluuFederation/gluu-gateway/commit/fc545c6b4ae05a384eb31285d813c50bc41af22a
