### ISSUE TITLE
GluuGateway within kubernetes

### ISSUE THREAD

**Issue by liepaja** [GluuFederation/gluu-gateway#40]
Are there Docker images to run this gateway within kubernetes?

**Comment by willow9886** [comment]
Not yet. We're still working on the linux package. Stay tuned!

**Comment by codejamninja** [comment]
Any updates? It's been over a year.

**Comment by codejamninja** [comment]
Is there a way to use a remote kong installation so I can use the kong ingress controller?

**Comment by nynymike** [comment]
GG is licensed under the GLUU-SUPPORT license. You'll need to raise questions about it in the Gluu Support portal https://support.gluu.org
