### ISSUE TITLE
OpenId Connect user sessions with server side storage

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#407]
At the moment we store all user sessions data in a cookie.
This approach has some disadvantages:
- a cookie may be very large
- a cookie contains sensitive user data and maybe potentially compromised

Our test suite shows that cookie size may be very large, we had to increase nginx header buffers https://github.com/GluuFederation/gluu-gateway/commit/7bda29601a8c14ab5a8c1a2dcd4bb6c84e946d8b

The best practice where to store sensitive user data is to give an admin the choices:
- encrypted in cookie
- per box storage (nginx Lua shared dictionary)
- separate storage (Redis, Memcached)

IMO it would be good enhancement for our gluu-openid-connect plugin.

We use lua-resty-session module which support all mechanisms listed above, so it will not a big deal, just some configuration would be required.

@nynymike @willow9886 @ldeveloperl1985, waiting for your feedback.

**Comment by ldeveloperl1985** [comment]
Agreed :+1:

**Comment by ldeveloperl1985** [comment]
Done, Covered it in https://github.com/GluuFederation/gluu-gateway/issues/430
