### ISSUE TITLE
Python script - installation failed.

### ISSUE THREAD

**Issue by liepaja** [GluuFederation/gluu-gateway#41]
Looks like error at the npm part.
```
Configuring postgres...
ALTER ROLE
CREATE DATABASE
CREATE DATABASE
Installing konga node packages...
Creating konga oxd client used to call oxd-https endpoints...
Installation failed. See:
  gluu-gateway-setup.log
  gluu-gateway-setup_error.log
for more details.
```

Error log:
[gluu-gateway-setup_error.log](https://github.com/GluuFederation/gluu-gateway/files/1768341/gluu-gateway-setup_error.log)

**Comment by nynymike** [comment]
We have not shipped this product yet. It's currently slated for release at the same time as Gluu Server 3.1.3
