### ISSUE TITLE
Add spontaneous scopes support to GG

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/gluu-gateway#410]
GG should be able to allow register regexp for resource. It should allow dynamically map path to scopes.

Example:
```
/user/1
...
/user/n
```

RS (GG) protects path with scopes. For this use case RS (GG) registers resource (resource_users) with path /users and scope /users/{} (oxd /uma-rs-protect). On GS (oxauth) we map policy to /users/{}.

During ticket registration GG should register explicit scope, e.g. `/user/1`, `/user/2`.

oxAuth ticket:
https://github.com/GluuFederation/oxAuth/issues/1133

Flow explanation can be found in comment:
https://github.com/GluuFederation/oxAuth/issues/1133#issuecomment-521193422

**Comment by altexy** [comment]
IMO we need to a way to capture a wildcard/regexp element from the path.
The simplest way is to use numbered captures, for example:
Protected path `/user/?/??` , contains 2 variable elements, so has 2 captures.
Real request path `/user/123abc/balance/history`.
First capture returns `123abc`.
Second - `balance/history`

We may use some placeholders within scope definition, say `{1}` 
IMO it would be the usual case when protected path contains only one variable element.
To simplify notation we may treat `{}` as `{1}`.

IMO using `??` multiple-wildcards element as capture should be prohibited as too wide.

When upon a request we may construct spontaneous scope.
GS expects PCRE, so
The `?` should be translated to `[^\/]+`
The `{<regexp>}` should be translated by just removing `{}` placeholders.

All slashes must be escaped. @yuriyz Can we avoid it?
It depends on what is expected on GS side. On nginx, we specify regexp options by separate function argument, so no need to escape slashes which is used in PCRE as a separator between regexp and options.  

Now we are able to construct spontaneous scope for a particular request.

From https://github.com/GluuFederation/oxAuth/issues/1133#issuecomment-521193422:

> RS (GG) send to oxd /uma-rs-check-access with scope /users/2 (requested scope must match scope template registered during resource registration)

@yuriyz How we may specify a scope for `/uma-rs-check-access` endpoint?
I don't see any related field.

**Comment by yuriyz** [comment]
> All slashes must be escaped. @yuriyz  Can we avoid it?

Do you mean call to oxd ? Can you give example ?

>@yuriyz How we may specify a scope for /uma-rs-check-access endpoint?

There is additional `scopes` array parameter added in 4.2. It's already available but I can give link to docs because it's not picked up.  See https://github.com/GluuFederation/oxd/blob/master/oxd-server/src/main/resources/swagger.yaml#L1296

@shmorri would you please pick up 4.2 docs?

**Comment by yuriyz** [comment]
@altexy there is one gap. Right now it's not possible to register client as spontaneous in oxd. @duttarnab is working on it. https://github.com/GluuFederation/oxd/issues/409

**Comment by duttarnab** [comment]
Hi @altexy, I have completed and committed `point# 1` of ticket: https://github.com/GluuFederation/oxd/issues/409 in the `master` branch of oxd. 
Now you can register the client as spontaneous in oxd.

Built available at : https://ox.gluu.org/maven/org/gluu/oxd-server/4.2.0-SNAPSHOT/

**Comment by altexy** [comment]
> > All slashes must be escaped. @yuriyz  Can we avoid it?
> 
> Do you mean call to oxd ? Can you give example ?

The example:
1. Client register spontaneous scope  with regexp:
 `^/user/[^/]+$` - slash not escaped
 `^\/user\/[^\/]+$` - slash escaped
Which one is correct? But it wouldn't a part of GG workflow. 

@yuriyz 
UMA clients should be aware of the required spontaneous  scopes.
Is it useful? In order to access a protected (by UMA) resource client must know about details in advance.
IMO it would be more intuitive if a spontaneous scope is allowed for a resource based on protection document, the `resources` fields of `/uma-rs-protect`.

2.When GG receives a request construct spontaneous scope for a particular path, for example
`/users/123abc` - here no need for any escaping.

> There is additional `scopes` array parameter added in 4.2. It's already available but I can't give link to docs because it's not picked up. See https://github.com/GluuFederation/oxd/blob/master/oxd-server/src/main/resources/swagger.yaml#L1296

Thanks.

**Comment by altexy** [comment]
> UMA clients should be aware of the required spontaneous scopes.
> Is it useful? In order to access a protected (by UMA) resource client must know about details in advance.
> IMO it would be more intuitive if a spontaneous scope is allowed for a resource based on protection document, the `resources` fields of `/uma-rs-protect`.

@yuriyz I have looked at the latest docs about UMA spontaneous scopes.
I see that for UMA use case a client doesn't need to specify spontaneous scopes during registration.
The spontaneous scope is attached to a resource.
So, sorry for the noise. All looks ok.

**Comment by altexy** [comment]
@yuriyz how does GS distinguish static vs spontaneous scopes for a resource?

**Comment by yuriyz** [comment]
> @yuriyz how does GS distinguish static vs spontaneous scopes for a resource?

It's distinguished by scopeType (with value spontaneous).

> re: escapes

I guess we have to escape it but maybe there is possibility to trick oxd jackson mapper. Can you open improvement ticket on oxd and assign to @duttarnab on 4.2 milestone ?

**Comment by altexy** [comment]
> > @yuriyz how does GS distinguish static vs spontaneous scopes for a resource?
> 
> It's distinguished by scopeType (with value spontaneous).

How I can specify the type of scope while calling `/uma-rs-protect` endpoint?

> 
> > re: escapes
> 
> I guess we have to escape it but maybe there is possibility to trick oxd jackson mapper. Can you open improvement ticket on oxd and assign to @duttarnab on 4.2 milestone ?

IMO it should be transparent for oxd, because oxd doesn't consume regexp, it just delivers the scopes (strings). GS consumes regexp.

---

Suppose a client doesn't use oxd and want to access GS directly using OAuth2/OpenId connect/UMA specs. Is it possible to request `allow_spontaneous_scopes` and `spontaneous_scopes` upon registration?

---

https://github.com/GluuFederation/oxd/blob/master/oxd-server/src/main/resources/swagger.yaml#L1296
Swagger above in `register_site.spontaneous_scopes`  field contains examples which are not correct IMO and may confuse the readers.
```
              spontaneous_scopes:
                type: array
                description: list of spontaneous scopes (regexp against which validation is performed).
                items:
                  type: string
                  example: ["/user/?/??", "/user/123abc/balance/history"]
```
"/user/?/??" uses our protected resource wildcard notation, which is not correct PCRE.
The correct example maybe something like `"^\/user\/[^\/]+\/.+$"`

**Comment by yuriyz** [comment]
> How I can specify the type of scope while calling /uma-rs-protect endpoint?

Why do you need to specify type ? It's internals of GS, GG shouldn't care about it. Just pass scope as before.

> Is it possible to request allow_spontaneous_scopes and spontaneous_scopes upon registration?

Yes.

> re: regexp

Right, GS expects correct and valid regular expression.

**Comment by yuriyz** [comment]
@duttarnab Aletexy is right, example in swagger.yaml is wrong. Can you correct it?

**Comment by altexy** [comment]
> > How I can specify the type of scope while calling /uma-rs-protect endpoint?
> 
> Why do you need to specify type ? It's internals of GS, GG shouldn't care about it. Just pass scope as before (e.g. `^/user/.+$`). Important point is to map UMA RPT Policy to it if needed which has to be done manually.

Hm, it is still not clear for me. 

Suppose I have 2 resources, for the first one I want to require a fixed scope, say `manager.edit`.
For a second I want spontaneous scope and specify `^/user/.+$`.
I protect both resources by `/uma-rs-protect`, passing above scopes.

How GS distinguish that first scope is fixed and second is spontaneous (need to regexp match)?
Shall a UMA client register `^/user/.+$` spontaneous  scope upon registration?

**Comment by yuriyz** [comment]
GS will try to match it both as normal and as spontaneous, so no need to specify type. Also for UMA case no need to register scope for client, it's required for resource. However in Connect case it is required to register spontaneous scope for client (because we don't have UMA Resource in Connect case).

**Comment by altexy** [comment]
> GS will try to match it both as normal and as spontaneous, so no need to specify type.

OK. Not optimal IMO approach, but still workable. Regexp usually starts with `^` and near to zero chances that we would have fixed scope started with the same char. Otherwise, it may create some vagueness. 

> Also for UMA case no need to register scope for client, it's required for resource. However in Connect case it is required to register spontaneous scope for client (because we don't have UMA Resource in Connect case).

Make sense.

**Comment by duttarnab** [comment]
> @duttarnab Aletexy is right, example in swagger.yml is wrong. Can you correct it?

@altexy, we have corrected example in swagger.yml. 

ticket: https://github.com/GluuFederation/oxd/issues/409 is completed and checked in to master branch of oxd.

**Comment by altexy** [comment]
This task should be decomposed into 2 issues, because the workflows are very different:
1. Add support spontaneous scopes for gluu-oauth-pep
2. Add support spontaneous scopes for gluu-uma-pep

**Comment by altexy** [comment]
Close this in favor of #414 and #415
