### ISSUE TITLE
Add spontaneous scopes support to gluu-oauth-pep

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#414]
Root ticket #410

Here we should be able to specify a spontaneous scope(s) within our scope expressions.
We should match the particular scope of a token against regexp.

IMO, we may use `^` char at the beginning of scope as regexp mark.

**Comment by altexy** [comment]
We should use the same path captures as in #415 to match path and scopes but on GG side.

So we would be able not only check that scope match some regexp, but also match the path.

IMO we should use the same {}, {1},... {n} notation to include the captured from the path.
The similar notation for both plugins is a good approach.

**Comment by ldeveloperl1985** [comment]
Done and docs updated

https://github.com/GluuFederation/docs-gg-prod/blob/4.2/docs/source/plugin/common-features.md#spontaneous-scope

https://github.com/GluuFederation/docs-gg-prod/blob/4.2/docs/source/admin-guide/consumer-config.md#make-oauth-client
