### ISSUE TITLE
Add spontaneous scopes support to gluu-uma-pep

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#415]
Root ticket #410 

The flow:
1. The resource should be protected on GS (by `/uma-rs-protect`) with some scopes with regexp instead of fixed scopes. For example, protected path `/user/?/??`, scope `^user:.+$`
See discussion in Item 3 about spontaneous scopes notation in UI, gluu-uma-pep config and for `/uma-rs-protect`.

2. RP requests /users/2/command on RS (GG).

3. GG matches the path/method, see no RPT, request a ticket from GS, specify path `/user/?/??` and scope `user:2`.
How the scope above is constructed?
We capture the first `?` or {<regexp>} in the protected path and replace the variable path in the spontaneous scope.
IMO we need two spontaneous scopes representations, first as PCRE (for GS) and second for GG usage.
For the GG we need to use captured from a path to construct a spontaneous scope.

We may use some placeholders within scope definition, say {1}
IMO it would be the usual case when protected path contains only one variable element.
To simplify notation we may treat {} as {1}.

On UI side an admin should be able to enter {}, {1}, {n} within scope field.

But when we call `/uma-rs-protect` we need to specify PCRE instead of {} notation.
The ? should be translated to [^\/]+
The {<regexp>} should be translated by just removing {} placeholders.

4. RP requests RPT with ticket, get back RPT authorized with permission for the resource `/user/?/??` and scope `user:2`. IMO spontaneous scope interception script should be invoked and scope persists for some time.

5. RP sends request to RS (GG), GG match the path/method, see RPT and check access on GS. GS sees `user:2` scope, match it with `^user:.+$` scope and invoke linked policy. Allow on policy success.

6. GG passes the request to upstream.

@yuriyz the workflow above is a bit different (items, 4, 5) from https://github.com/GluuFederation/oxAuth/issues/1133#issuecomment-521193422.
Please, fix me if I'm wrong.

**Comment by yuriyz** [comment]
Step 5 should be corrected. Permission is granted during RPT authorization (step 4), thus policy is invoked at RPT authorization. At step 5 we don't invoke policy and also don't check spontaneous scope, at step 5 we check fixed/static scope of RPT which is already granted at step 4 (match requested scope to RPT permissions scopes). 

Otherwise looks good.

**Comment by altexy** [comment]
@yuriyz thanks

**Comment by ldeveloperl1985** [comment]
@altexy could you please provide some more examples?. Also how to deal with multiple dynamic scope? 

| Path register for GG and GS | GS PCRE scope | GG  scope |
|----------------------------------------|------------------------|----------------|
|/posts/?|-|-|
|/users/?/image/?|-|-|
|/comments/??|-|-|
|/products/??/orders/??|-|-|
|/account|-|-|

**Comment by altexy** [comment]
@ldeveloperl1985 maybe this page would help https://github.com/GluuFederation/gluu-gateway/wiki/Spontaneous-scopes

**Comment by altexy** [comment]
@ldeveloperl1985 Mike is not sure should we invest our efforts for this feature.
Let's concentrate on #414

**Comment by ldeveloperl1985** [comment]
Ok Sure :+1:

**Comment by nynymike** [comment]
Waiting for demand to materialize
