### ISSUE TITLE
resty/hmac.lua throwing error in kong 1.5

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#418]
```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:620: error loading module 'kong.plugins.gluu-oauth-auth.handler':
/usr/local/share/lua/5.1/resty/hmac.lua:81: size of C type is unknown or too large at line 44
stack traceback:
	[C]: in function 'cdef'
	/usr/local/share/lua/5.1/resty/hmac.lua:81: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/resty/jwt.lua:5: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/gluu/kong-common.lua:4: in main chunk
	[C]: in function 'require'
	...al/share/lua/5.1/kong/plugins/gluu-oauth-auth/access.lua:2: in main chunk
	[C]: in function 'require'
	...l/share/lua/5.1/kong/plugins/gluu-oauth-auth/handler.lua:2: in main chunk
	[C]: at 0x7fbd0dd06bf0
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
	init_by_lua:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:620: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
	init_by_lua:3: in main chunk

```

**Comment by altexy** [comment]
@ldeveloperl1985 can you provide steps to reproduce?
I don't see such error in gluu-oauth-auth test.
But, strange, again see 
```
2020/01/30 12:17:52 [error] 32#0: *4 failed to run log_by_lua*: ...ocal/share/lua/5.1/kong/plugins/gluu-metrics/metrics.lua:64: attempt to index field 'service' (a nil value)
stack traceback:
	...ocal/share/lua/5.1/kong/plugins/gluu-metrics/metrics.lua:64: in function 'log'
	...ocal/share/lua/5.1/kong/plugins/gluu-metrics/handler.lua:21: in function <...ocal/share/lua/5.1/kong/plugins/gluu-metrics/handler.lua:18>
	/usr/local/share/lua/5.1/kong/init.lua:209: in function 'execute_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1068: in function 'log'
	log_by_lua(nginx-kong.conf:95):2: in main chunk while logging request, client: 172.19.0.1, server: kong, request: "HEAD / HTTP/1.1", host: "127.0.0.1:33123"
```

**Comment by altexy** [comment]
@ldeveloperl1985 
OK, I see in rocket chat that it is on local and server installation.
Which OpenSSL version do you have locally on both systems?

**Comment by ldeveloperl1985** [comment]
In my local 
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
------------------------------------------------------
On Server
```
# openssl version
OpenSSL 1.1.1  11 Sep 2018
```

**Comment by ldeveloperl1985** [comment]
we are using **kong 1.5.3**, is it ok?

**Comment by altexy** [comment]
> we are using kong 1.5.3, is it ok?

Kong 1.5.0 was released some days ago.
Don't know anything about Kong 1.5.3

Where do you get it?

**Comment by ldeveloperl1985** [comment]
our package team found this version. if you are not ok then we can request to build a package with kong 1.5.0.
@nikdavnik could you please share the kong 1.5.3, download link?

**Comment by altexy** [comment]
I believe the latest Kong requires OpenSSL 1.1.1

**Comment by ldeveloperl1985** [comment]
Yes, we have OpenSSL 1.1.1. on the server but getting the same problem in the server also.
```
# openssl version
OpenSSL 1.1.1  11 Sep 2018
```

**Comment by nikdavnik** [comment]
link for ubuntu18 kong 1.5.3
https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.5.3.bionic.amd64.deb

**Comment by altexy** [comment]
Yes, I see Kong 1.5.3 release, but it looks very strange because I don't see  1.5.3 version  here - https://github.com/Kong/kong/blob/master/CHANGELOG.md and on Dockerhub https://hub.docker.com/_/kong.

Let's try with Kong 1.5.0

**Comment by altexy** [comment]
And most important why 1.5.1 and 1.5.2 are skipped?

**Comment by ldeveloperl1985** [comment]
Ok, let's try with Kong 1.5.0

**Comment by altexy** [comment]
BTW I see the error with Kong 2.0.0, so we will need to deal with it soon very likely.

**Comment by ldeveloperl1985** [comment]
@altexy  Tested new builds with Kong 1.5.0. It is working in Ub18 but getting same problem in Ub16.
Do you have any solution or do we need to revert back to Kong 1.3.0?

**Comment by altexy** [comment]
@ldeveloperl1985 I spent some time, but still don't understand the reason.
We may revert if we need GG 4.1 asap.

**Comment by ldeveloperl1985** [comment]
I think we need to revert back and use kong 1.3.
What do you think @nynymike ?

**Comment by altexy** [comment]
@ldeveloperl1985 @nynymike 
I have some progress here, let me some time, please.

**Comment by altexy** [comment]
@ldeveloperl1985 can you, please, test with the branch `kong_2.0`?

The Kong 1.5 requires near to the same changes as 2.0, so I bumped version to the latest Kong.

**Comment by ldeveloperl1985** [comment]
@altexy  failed to clone submodule `lua-resty-hmac`
```
Unable to checkout 'c373d78139fcae4c67dad6884a9f0bd78315f3c0' in submodule path 
'third-party/lua-resty-hmac'
```

**Comment by altexy** [comment]
@ldeveloperl1985 I have fixed git submodule error.
The history of `kong_2.0` branch was fixed.
Keep in mind - after checkout `kong_2.0` branch you will possibly need to resync submodules:
```
git submodule sync
git submodule update --init --recursive
```

**Comment by ldeveloperl1985** [comment]
@altexy i've check services, routes and plugins configuration with Konga UI and it is working good so could you please make a PR and let's merge it into version_4.1

**Comment by altexy** [comment]
@ldeveloperl1985 Great! Will do it immediately
