### ISSUE TITLE
Move our forks under GluuFederation

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#419]
Now we use 2 git repo forks  with our fixes:
lua-resty-jwt (forked from https://github.com/cdbattags/lua-resty-jwt/ to https://github.com/altexy/lua-resty-jwt)

lua-resty-hmac (froked from https://github.com/jkeys089/lua-resty-hmac to https://github.com/altexy/lua-resty-hmac)

### lua-resty-jwt

- some new enc algorithms added by us (RS386, ES* - coming soon)
- make possible to use digital key (avoid converting from text PEM upon every operation)

### lua-resty-hmac

- FFI definition fix compatible with Kong 2.0

IMO both repos should be transferred to the GluuFederation organization on github.

@willow9886  We need 2 new blank git repositories (without initial commit):
`lua-resty-jwt` and `lua-resty-hmac`

**Comment by shmorri** [comment]
Both are now transferred. [Here](https://github.com/GluuFederation/lua-resty-jwt) and [here](https://github.com/GluuFederation/lua-resty-hmac)

**Comment by altexy** [comment]
Now we need to point to these git repos in our submodules
