### ISSUE TITLE
Sometime Getting 400 from kong

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#424]
Reproduce problem:
1. configured oidc(with 2FA) + uma plugin
2. request to proxy
3. request for uma
4. request for 2fa OTP
5. once you get back to kong, you will face a problem 

Please check logs, in error.log there is nothing but in access.log, there is 400. I am facing this issue in my local, try to reproduce it on dev1 but not getting success yet. it is working well on dev1. It is only occurring after 2FA.
[access.log](https://github.com/GluuFederation/gluu-gateway/files/4191934/access.log)
[error.log](https://github.com/GluuFederation/gluu-gateway/files/4191935/error.log)

Please check video here https://we.tl/t-o9Udy5e7Ri

**Comment by altexy** [comment]
@ldeveloperl1985 400 HTTP code means Bad request.
Nginx core blocks it at the very early state, Lua code never sees it.

It would be useful to catch the problem request.
Is it possible?

**Comment by ldeveloperl1985** [comment]
@altexy I am testing with only the `GET` HTTP request so in request I think there is no problem. any other idea?

**Comment by altexy** [comment]
> @altexy I am testing with only the `GET` HTTP request so in request I think there is no problem. any other idea?

Just sniff the 400 requests by any tools and post it here.

**Comment by ldeveloperl1985** [comment]
> Just sniff the 400 requests by any tools and post it here.

Sorry not getting you, I am requesting a protected path in the browser. You can check the above video.

**Comment by altexy** [comment]
> > Just sniff the 400 requests by any tools and post it here.
> 
> Sorry not getting you, I am requesting a protected path in the browser. You can check the above video.

Can you show me the full details of the final HTTP request (on which you have 400 Bad request status code)?

Also I see a lot of HTTP/2.0 requests in access.log.
Do you really test the protected site with HTTP/2.0?

IMO we need to test GG with HTTP/2.0
We didn't spent enough attention to HTTP/2.0

**Comment by ldeveloperl1985** [comment]
1. `https://gluu.local.org:9443/payments/` this URL I am requesting in the browser.
1. here is my plugin config 
![Screenshot](https://user-images.githubusercontent.com/2329776/74641844-00e35a00-5198-11ea-9b30-4d3a126aacb2.png)
below is oidc plugin config
```json
{
  "created_at": 1581424276,
  "config": {
    "custom_headers": [
      {
        "iterate": true,
        "value_lua_exp": "id_token",
        "sep": " ",
        "header_name": "http-kong-id-token-{*}",
        "format": "string"
      },
      {
        "iterate": true,
        "value_lua_exp": "userinfo",
        "sep": " ",
        "header_name": "http-kong-userinfo-{*}",
        "format": "string"
      },
      {
        "iterate": false,
        "value_lua_exp": "userinfo",
        "sep": " ",
        "header_name": "http-kong-userinfo",
        "format": "jwt"
      },
      {
        "iterate": false,
        "value_lua_exp": "id_token",
        "sep": " ",
        "header_name": "http-kong-id-token",
        "format": "jwt"
      }
    ],
    "max_id_token_auth_age": 3600,
    "required_acrs_expression": "[{\"path\":\"/payments/?\",\"conditions\":[{\"httpMethods\":[\"?\"],\"required_acrs\":[\"otp\"],\"no_auth\":false}]}]",
    "logout_path": "/logout",
    "requested_scopes": [
      "openid",
      "oxd",
      "email",
      "profile",
      "uma_protection"
    ],
    "post_logout_redirect_path_or_url": "/logout_redirect_uri",
    "client_id": "833fbc8f-cdb3-41b1-866a-6c860dc2ad63",
    "op_url": "https://gluu.local.org",
    "authorization_redirect_path": "/callback",
    "oxd_id": "65b4b80d-062f-4f79-adde-2784ad7a62e7",
    "max_id_token_age": 3600,
    "oxd_url": "https://localhost:8553",
    "client_secret": "c6856c54-4bd0-475a-b62b-a8e8b777fdbe"
  },
  "id": "065751a0-886b-46d9-85e4-64b79d7d9f0c",
  "service": null,
  "enabled": true,
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "name": "gluu-openid-connect",
  "consumer": null,
  "route": {
    "id": "4d3f743f-859b-48d5-ba6b-141b17eb9b23"
  },
  "tags": null
}
```

If I directly request this `/payments/` endpoint, OTP 2fa happens and I logged in successfully. I am not getting problem when I first hit this endpoint
but
if I hit `https://gluu.local.org:9443` then basic oidc auth happens and logged in successfully after this I am requesting `/payments`, OTP 2FA happens and when I get back to `/payments/`, here I am facing a problem.
Sometimes once I get back it is working but sometimes the same 400 problems. but this is happening only after OTP 2FA auth protected path. also sometimes `/settings` which is UMA claim gathering flow protected.

> IMO we need to test GG with HTTP/2.0
How? I am registering resources in GG and simply requesting in the browser. anything we need to do for HTTP/2.0? If Yes then please provide info I'll test.

**Comment by altexy** [comment]
@ldeveloperl1985 I spent some time debugging the issue.
IMO 400 error is produced not by GG but by upstream service.
Very likely it is related to huge cookie header we have after OTP auth.

IMO we need to hide our session cookie from upstream services, I did a try but no success so far.

Can you, please, tell me how to check logs files of the upstream service used for `/payments` path?
I believe it is node app, but was not able to find logs.
I need to be sure that 400 is produced by protected service.

**Comment by ldeveloperl1985** [comment]
you can check logs by `pm2 logs index` but I have just checked there is not any crash report at upstream app.

**Comment by ldeveloperl1985** [comment]
@altexy  I am getting this in `/settings` in UMA claim gathering
```
2020/05/14 07:30:25 [warn] 23496#0: *224692 [kong] access.lua:232 [gluu-uma-pep] request to the claim redirect response path but there's no session state found, client: 103.251.59.161, server: kong, request: "GET /claims_callback?state=adrevq9kcsqpg2ii1uvid5ltu6&ticket=a72af784-d290-426f-acfc-6d04e54b5c99 HTTP/1.1", host: "gg-test.gluu.org", referrer: "https://ce-dev6.gluu.org/oxauth/uma2/sample/city.htm"
```

Have you changed anything on gg-test?

**Comment by altexy** [comment]
@ldeveloperl1985 yes, I have the proof that 400 responses are generated by upstream service.
I have hidden our cookie and `/payments` now works, but it also require changes in gluu-uma-pep plugins, because it also uses cookie. I have made 2 separate cookies for both plugins, but https://github.com/bungle/lua-resty-session#sessionhide works not as expected - it removes all cookies. When I try to remove its own cookie in gluu-openid-connect plugins - it also removes cookie of gluu-uma-pep plugins.

Today in the afternoon I will try to find to solve this issue.

**Comment by altexy** [comment]
@ldeveloperl1985 I have found the problem in lua-resty-session.

When we hide (from upstream) one session other sessions became not accessible.
I have implemented the workaround, but it requires a fix to lua-resty-session library.

I have forked the lib and implemented the fix. 
It is not the final version - I need to add a test to ensure that up[stream does see session cookie.

**Comment by altexy** [comment]
I tried to push my fixes to upstream lua-resty-session, but with now success so far.
https://github.com/bungle/lua-resty-session/pull/100
If I will not get any feedback soon - we will need to fork the repo under GluuFederation umbrella.

**Comment by bungle** [comment]
@altexy, I'll check it tomorrow, and push `3.5`. Thank you.

**Comment by altexy** [comment]
> @altexy, I'll check it tomorrow, and push `3.5`. Thank you.

Great!

**Comment by bungle** [comment]
@altexy / @ldeveloperl1985,

The `lua-resty-session` `v3.5` has now been released (https://github.com/bungle/lua-resty-session/releases/tag/v3.5). Also available at `LuaRocks` (https://luarocks.org/modules/bungle/lua-resty-session/3.5-1)  and `OPM` (https://opm.openresty.org/package/bungle/lua-resty-session/).

I made some refinements to @altexy's original fix to make the `session:hide` even more robust. Let me know if you have any further issues. Thanks for reporting and fixing it in a first place!

**Comment by altexy** [comment]
@bungle thank you, the latest lua-resty-session master works for us

**Comment by ldeveloperl1985** [comment]
Fixed
