### ISSUE TITLE
Don't Send Access Token to Upstream API

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#428]
Sending an access token is dangerous--you have to really trust the upstream API. In some cases, it would be better if GG uses the access token for security, but does not forward it along to the upstream API.

**Comment by altexy** [comment]
@nynymike it is fully configurable.
We have `pass_credentials` field with possible values:
- `pass` - pass access token upstream
- `hide` - remove Authorization header
- `phantom_token` - send access token introspection result as JWT (not signed)

The default is `pass`, but we can change it to `hide` if you think it is better.

**Comment by ldeveloperl1985** [comment]
@nynymike it is configurable so can we close this issue?
