### ISSUE TITLE
OpenID-Connect plugin, path with no authentication

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#429]
https://support.gluu.org/access-management/8092/fetch-attribute-for-unprotected-pages/

We may sent a set of headers (fully configurable) to upstream server based on user session.

The use case:
1. Path `/app/??` require an acrs
2. Path  `/??` (any others) doesn't require authentication at all
3. Client access root page - no header sent to upstream
4. Client access protected path `/app/anything` - redirected to OP and back
5. Headers are sent to upstream
6. Client again access root page - no headers are sent, but client expects headers because there is live user session with all required information.

The current code just doesn't send headers for path with no required authentication.

@nynymike We may implement the behavior as expected by customer, it will require IMO 8 - 12 hours.

Shall we include it in 4.2 roadmap?

**Comment by nynymike** [comment]
Approved, please proceed.
