### ISSUE TITLE
Configure lua-resty-sessions parameters

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#430]
We store OpenID Connect user session info in a cookie.
It may be big enough to produce an error on some HTTP servers.
Our GG nginx is specially prepared for big headers.

IMO it would be more correct to not send our cookie header upstream.

@nynymike @ldeveloperl1985 - please post your feedback.

**Comment by nynymike** [comment]
Agreed. IMHO, cookie should contain only session reference identifier, not values.

**Comment by altexy** [comment]
@nynymike we may make it configurable very simple, because library allows the next chioces:
- store session data in cookie
- in cookie only id, store data in nginx storage, work well for single node GG deployment
- in cookie only id, store data in Redis. 

The decision would be GG admin - does he want small cookie for the price of supporting Redis cluster for GG cluster.

**Comment by nynymike** [comment]
Awesome, I like it.

**Comment by altexy** [comment]
It turned out that removing only our session cookie is not trivial.
We need to get all cookie header (as table in Lua) interate thru all and remove only our cookies.
In order to distinguish our cookie we may define our cookie name, for example, `gluu-oidc-session`.
It may be done in Lua code with low efforts.

But cookie filtering, as explained above, is expensive operation which we need to perform on every request with our session.

IMO we may offer as workaround the cookie storage configuration, as well as all others lua-resty-session configuration.

**Comment by altexy** [comment]
The configuration of resty-session library may be done in 2 ways:
- injecting nginx directives
- explicit configuration on plugin level.

With 4.1 version we may document how to do the configuration by injecting nginx directives.
resty-sessions settings would be global for all plugins.

Not sure what is better - global or per plugin resty-session configuration.

We need to test injecting directives approach first, preferably we should add a test case.

**Comment by altexy** [comment]
I have added a test case which shows that injecting lua-resty-sessions parameters in proxy's server nginx block works.
@ldeveloperl1985  We need to add a docs about it somehere.

The topic:
1. `session_secret` for cluster
2. Session storage configuration. We may refer to the https://github.com/bungle/lua-resty-session#pluggable-storage-adapters

**Comment by ldeveloperl1985** [comment]
Done and docs upldated https://github.com/GluuFederation/docs-gg-prod/blob/4.2/docs/source/plugin/gluu-openid-connect-uma-pep.md#session-configuration

**Comment by altexy** [comment]
Possible per-plugin lua-resty-session configuration we put on hold.
Let's see if there will be requests from customers for such a fine-tuning.
