### ISSUE TITLE
Update oauth client auth plugin to reflect new mode names

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#44]
I introduced shorter jargon for “kong_acts_as_uma_client” … now it’s just “Mix Mode”
versus “OAuth Mode” or “UMA Mode”. The checkbox labels should be updated.

**Comment by ldeveloperl1985** [comment]
Done in https://github.com/GluuFederation/gluu-gateway/commit/fb1c7004c41c99edfd71a87b5a42cc5a8edfd4ce
