### ISSUE TITLE
Handle POST request after OpenID Connect authentication and redirects

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#441]
We should backport this issue to 4.0 and add it to a new version.

This feature should be optional, enabled per plugin.
In order to implement this feature we need:
- save not only original_url, but also method, body and Content-Type
- instead of internal redirect which we use now we should change url/methods/body/header of current request to upstream

**Comment by altexy** [comment]
Hi @ldeveloperl1985 , not sure how to proceed with backporting this issue to 4.0
Please, review the code, if no objection - we will provide a patch to Sobhan Panda.
PS: Mike asked to implement this feature yesterday.

**Comment by altexy** [comment]
To be clear: commits above are for 4.0 the branch `441_restore_original_auth_params`, forked from `backport_refresh_pending_logic`.

This feature shall be implemented in 4.3 also using this ticket.

**Comment by ldeveloperl1985** [comment]
@altexy I reviewed the code. It is good, also test cases are passing. But as we add one more config property so for that I need to change the UI design also. Give me time for that. I'll push my UI changes in this same branch.

> This feature shall be also implemented in 4.3 also using this ticket.

@altexy  Why not in GG 4.2?

**Comment by altexy** [comment]
@ldeveloperl1985 
> Why not in GG 4.2?

I think we freeze 4.2, isn't it?

**Comment by ldeveloperl1985** [comment]
Hmm yes but let's check with @shmorri . If we have time then we should have to add it in GG 4.2. so @shmorri  when we are going to release GG 4.2?

**Comment by shmorri** [comment]
We're planning to release 4.2 on June 30th. The code freeze is scheduled for May 30th.

**Comment by ldeveloperl1985** [comment]
thanks @shmorri so @altexy we can proceed now.

**Comment by ldeveloperl1985** [comment]
Done https://github.com/GluuFederation/gluu-gateway/pull/442
