### ISSUE TITLE
Team based API visibility and access - high level design

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#446]
Originally discussed in https://github.com/GluuFederation/gluu-gateway-ui/issues/27.

The main point is that that the feature should be implemented in GG not in GG-UI.

GG-UI should support it.

**Comment by ldeveloperl1985** [comment]
I agree with the `Attach to every entity a tag in form of team:<team_name>`  but @altexy 
 same question how can we authorized??? because I can see we have only tag based filter and no custom entity for any protection. 

-------------------------------------------------------------------------

I think we can protect kong endpoint with `gluu-oauth-auth` and `gluu-oauth-pep` plugin with scope expression by `roles(team)` protection. Using interception script add user `roles` in scopes as like we are doing in angular demo https://gluu.org/docs/gg/tutorials/angular-oauth-role-security/

--------------------------------------------------------------------------

But admin has to put some effort to understand and configure this all things. admin has to configure oauth plugin with every entity endpoint(for read-GET, write-POST-PUT access) and add same team tag in every kong entity.

**Comment by nynymike** [comment]
I think protecting Kong config API's with OAuth makes **a lot** of sense. What we also need is a "developer portal." Some companies are building this as a standalone product. I think we can write a Casa plugin to handle these use cases:
1. Requesting client credentials
2. Requesting OAuth scopes for a client
3. (Admin) Reviewing OAuth scope requests by client
4. (Admin) Approving OAuth scope requests by client

I think we should use OAuth... not UMA for Kong API protection.

**Comment by altexy** [comment]
> but @altexy, same question how can we authorized???

We may use gluu-oauth-auth plugin for authentication.

IMO we cannot (and shouldn't) use gluu-oauth-pep for authorization, because it is completely path oriented.

We should create specific plugins for this purpose. Let's name it gluu-admin-pep.
IMO this new plugin should do the following:
- check the token for `team:<team_name>` scope. Without such scope, access should be forbidden.
- man-in-the-middle - transform all requests by adding a `team:<team_name>` tag for every POST entity operation, add filtering by tag for GET requests, ensure that the entity in its own team for PUT and PATCH, etc.
- if we need more fine granular access (inside a team) we may introduce roles scopes.
- we may use a superadmin scope for superadmin which is able to see all details as it is.

The last man-in-the middle function will limit Kong admin API for teams member, I wrote  about it in my previous post, we need to research all details here to check possible corner cases when tag filtering may not work. Hope it will be rare case - we may found a workarounds, by additional lookups, etc.

> because I can see we have only tag based filter and no custom entity for any protection

The idea of using team's tags is to avoid Kong custom entities. All metainfo about team is attached to an entity as a tag. Our gluu-admin-pep plugin must ensure that this tag is proper maintained for all entities.

> But admin has to put some effort to understand and configure this all things. admin has to configure oauth plugin with every entity endpoint(for read-GET, write-POST-PUT access) and add same team tag in every kong entity.

IMO GG admin wouldn't need a lot of such details, we should document that Kong admin port should be protected by gluu-oauth-auth + gluu-admin-pep plugins with minimal configuration.
We rely on proper scopes from GS. 

> I think protecting Kong config API's with OAuth makes a lot of sense. What we also need is a "developer portal." Some companies are building this as a standalone product. We are not an API managmeent platform, but I think we can write a Casa plugin to handle these use cases offering a base level of functionality:

Sure. The final solution would be combination of GS + GG + Casa + some custom plugins/configuration. But GG part completely relies on scopes convention.

BTW I know there are a lot of people which think that OAuth2 scopes are not for authorization, but only for delegation scenario. https://auth0.com/blog/on-the-nature-of-oauth2-scopes/

**Comment by ldeveloperl1985** [comment]
> IMO we cannot (and shouldn't) use gluu-oauth-pep for authorization, because it is completely path oriented.
We should create specific plugins for this purpose. Let's name it gluu-admin-pep.

Agree, let's make a new plugin for this.

> if we need more fine granular access (inside a team) we may introduce roles scopes.
we may use a superadmin scope for superadmin which is able to see all details as it is.

I think we can add this. we just need one more scope. One for Team and second for Role.

**Comment by altexy** [comment]
Many Kong entities may have a name.
The name must be unique per Kong cluster.
In order to provide a separate namespace for a team we will have to add `team_<team_name>_` prefix to all names.
It will require name transformation in both directions:
- adding prefix upon by all requests with name included in the path
- strip prefix when retrieving entities information

It is an expensive operation, but IMO Kong admin API is not designed for high performance throughput, so it is acceptable.

**Comment by altexy** [comment]
> Filtering by tags is not supported in foreign key relationship endpoints. For example, the tags parameter will be ignored in a request such as GET /services/foo/routes?tags=a,b

IMO teams will be completely disjoint sets. 

So for foreign key relationship endpoints we may first check the team of root object, then retrieve linked without tag filtering.

**Comment by ldeveloperl1985** [comment]
> The name must be unique per Kong cluster.
In order to provide a separate namespace for a team we will have to add team_<team_name>_ prefix to all names.

Add prefix to all kong entities name? if yes then why we need to do this? because kong is already validating unique name validation for entities.

**Comment by altexy** [comment]
Members of different teams will not understand why this name is not allowed.
As I understand the core design - team members should be able to view only its own team's entities.

**Comment by ldeveloperl1985** [comment]
Ok Agree

> So for foreign key relationship endpoints we may first check the team of root object, then retrieve linked without tag filtering.

Agree

**Comment by altexy** [comment]
IMO a deployment should be predictable. Member of a team should be able to write a script with hardcoded names without headache of finding unique names in case of conflicts with others teams.

If we recommend a prefix - we allow bad behaved another team member to influence our team.

**Comment by altexy** [comment]
This feature has been put on hold.

**Comment by nynymike** [comment]
We are not going to implement this feature.
