### ISSUE TITLE
Use gluu icosahedron as favicon

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#5]
We need to supply a nicer favicon for Gluu Gateway

![image](https://user-images.githubusercontent.com/3717101/34060470-84dfe190-e1a9-11e7-9733-f97e9de31d3b.png)

**Comment by willow9886** [comment]
See attached. 

![icosahedron-transparent](https://user-images.githubusercontent.com/5271048/34082325-678b6c6c-e321-11e7-9fe6-0b86268e2bf1.png)

**Comment by ldeveloperl1985** [comment]
@nynymike  you need to clear your browser cache or try in private window of browser.

**Comment by nynymike** [comment]
ok, looks better... but the favicon is not transparent. Compare with another gluu site:
![image](https://user-images.githubusercontent.com/3717101/34303891-1559cabc-e6fd-11e7-856d-0e43437966d9.png)
