### ISSUE TITLE
Maintain legacy OAuth headers 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#52]
Kong defines a few headers: 

https://getkong.org/plugins/oauth2-authentication/#upstream-headers

We will need to add 

```
* X-Consumer-ID, the ID of the Consumer on Kong
* ADD THIS TO PLUGIN & KONGA: X-Consumer-Custom-ID, the custom_id of the Consumer (if set)
* X-Consumer-Username, the username of the Consumer (if set)
* ADD THIS FOR OAUTH2 CLIENTS ONLY: X-Authenticated-Scope, the comma-separated list of scopes that the end user has authenticated, if available (only if the consumer is not the 'anonymous' consumer)
* OMIT: X-Authenticated-Userid, the logged-in user ID who has granted permission to the client (only if the consumer is not the 'anonymous' consumer)
* X-Anonymous-Consumer, will be set to true when authentication failed, and the 'anonymous' consumer was set instead.
```

**Comment by nynymike** [comment]
1. I do not see any way for the admin to populate the `X-Consumer-Custom-ID` header in Konga.
2.  `X-Consumer-Custom-ID` I think this also needs a Yes|No form control

**Comment by ldeveloperl1985** [comment]
You can set custom_id of a consumer using [Consumer section](https://github.com/GluuFederation/gluu-gateway#4-consumers)
![4_customer_add](https://user-images.githubusercontent.com/2329776/38236780-ddf7cd3a-3742-11e8-9fac-32b09b77b2d8.png)

Currently, there is no way for an admin to hide/show from the header, it by default adds in the header after successful authentication.

https://github.com/GluuFederation/gluu-gateway/blob/master/gluu-oauth2-client-auth/kong/plugins/gluu-oauth2-client-auth/access.lua#L138

**Comment by nynymike** [comment]
This is an id distinct from the consumer id... it is present in the default kong oauth plugin

**Comment by ldeveloperl1985** [comment]
Added a field for show and hide consumer custom id from header.

![claim_header](https://user-images.githubusercontent.com/2329776/38308847-f44eb474-3835-11e8-920b-ff84e7ab96d6.png)
