### ISSUE TITLE
Gluu Gateway should provides java

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-gateway#62]
I offer to do:
1. Add server-jre-8u162-linux-x64.tar.gz to to /opt/dist/app
2. Add command to installJRE. Here is method from CE setup: https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L1120
3. Add to /etc/profile
```
export JAVA_HOME=/opt/jre
```

**Comment by yurem** [comment]
Instead of updating /etc/profile we can use modern style to update system variables:
We need to create /etc/profile.d/jre-gluu.sh with:
```
export JAVA_HOME=/opt/jre
export PATH=$PATH:$JAVA_HOME/bin
```

**Comment by yurem** [comment]
`/etc/profile.d/jre-gluu.sh` should has 644 permissions and `root:root` user:group

**Comment by ldeveloperl1985** [comment]
Tested in build [55](https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-gateway_0.1-55~trusty+Ub14.04_amd64.deb). Everything working well
