### ISSUE TITLE
Restrict API's Consumer can access

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#65]
In the OAuth2 client authentication section of the consumer configuration, we should add a method to `Enable` or `Disable` API restriction.  If enabled, the admin can click on a link to launch a modal window to search for and select available API's.  The client can only call specified API's if client restriction is enabled.

![image](https://user-images.githubusercontent.com/3717101/38459736-3990c272-3a73-11e8-8b76-b1cf6b04b995.png)

**Comment by ldeveloperl1985** [comment]
One question:
API's means available list of API's in API section? right?
![list_of_apis](https://user-images.githubusercontent.com/2329776/38498496-47cc4324-3c22-11e8-8cc4-418cba2e6969.png)

**Comment by nynymike** [comment]
correct

**Comment by ldeveloperl1985** [comment]
Completed

Step 1: Restricted API enable and disable option

![restricted_api_add](https://user-images.githubusercontent.com/2329776/38619925-eb283df4-3dba-11e8-8f28-24bae383ca1e.png)

Step 2: Select restricted API

![restrict_api](https://user-images.githubusercontent.com/2329776/38619859-bb61d030-3dba-11e8-917b-338db26986af.png)
