### ISSUE TITLE
Bug: no JDK installed error

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#71]
During the installation of GG, after the command
**apt install gluu-gateway**, the console shows an error about no JDK installed. This is not a blocker for the installation because JDK is later on installed in python setup-gluu-gateway.py.
Please remove the error message.

![no jdk error](https://user-images.githubusercontent.com/38302725/39105716-cce54be0-46fa-11e8-8864-8860fcefffe8.png)

**Comment by ldeveloperl1985** [comment]
@adrian-gluu , according to natalia(or end user) it is like bugs in setup so what can we do for this?

**Comment by ganesh-at-wiw** [comment]
#91 also mentions this.

**Comment by nikdavnik** [comment]
please check this package and confirm that issue have been fixed
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-gateway_3.1.3-6~trusty+Ub14.04_amd64.deb

**Comment by ldeveloperl1985** [comment]
I tested in my local VM machine and got the same thing. Please take a look. 
![err](https://user-images.githubusercontent.com/2329776/39873850-b02afa9e-5489-11e8-8c99-57e52e7d81eb.png)

**Comment by adrian-gluu** [comment]
that java warning is because now java is managed by setup not on installation

**Comment by kepuss** [comment]
@adrian-gluu @yurem 
We know that. But I would like to not have false alarms during installation. 
Could we do sth to prevent java check during installation?
Is it oxd-server trying to call java during installation?

**Comment by yurem** [comment]
I agree we need to fix this warning in oxd-server package.
These lines from `postinst` led to them:
```
/etc/init.d/oxd-server stop > /dev/null
/etc/init.d/oxd-https-extension stop > /dev/null
```

We can check if pid file exists before running them. Or we can just add ` 2>&1`.

I offer to use second approach. I think so because it also not run stop if service not configured yet. It just show warning.

**Comment by yurem** [comment]
I think we need to change milestone of this issue to 3.1.4 and move it to oxd-server.

**Comment by natt-tester** [comment]
There's no error about Java JDK anymore, well done! :D 
I've only found one suspiciously looking oxd-server.log part, please take a look @yurem:
https://ox.gluu.org/jenkins/view/GG/job/GG_Test_Deploy/58/console
![2018-05-12_19h11_25](https://user-images.githubusercontent.com/38302725/39955811-ee6c79c8-5618-11e8-9473-607cdf0e6dca.png)

**Comment by yurem** [comment]
It's not bug. But I agree with you. oxd should not print errors if finally it was started successfully We can open oxd-server issue for this

**Comment by natt-tester** [comment]
@yurem, please do! I'm closing this one as done.
