### ISSUE TITLE
GG login to Admin Panel flawed

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#73]
Please refer to the gif and look into the bug visible after the login; after providing the credentials and clicking the login button, the user is taken to the previous view, and there is an Error message displayed while loading the Dashboard:

![2018-04-23_14h17_04](https://user-images.githubusercontent.com/38302725/39106768-51e2af30-4701-11e8-9704-32b9c16ea556.gif)

**Comment by ldeveloperl1985** [comment]
Solved. Tested in the new build.
