### ISSUE TITLE
User information not displayed

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#8]
![image](https://user-images.githubusercontent.com/3717101/34272318-6e618f76-e655-11e7-94dc-fcc6229e9822.png)

![image](https://user-images.githubusercontent.com/3717101/34272181-f200f94e-e654-11e7-9e5f-30cff691dc27.png)

If Konga asked for `profile` as an OpenID Connect scope, why isn't the user being dynamically generated? Why doesn't the username display in the profile section? Also is the username noted in the logs?

**Comment by ldeveloperl1985** [comment]
Solved https://github.com/GluuFederation/gluu-gateway/commit/581e811c1a5799c344d259a64660c3fd45a11967
