### ISSUE TITLE
Post logout URI not passed

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#81]
After logging out of GG Admin Panel, I received this message: 
![2018-04-27_12h23_14](https://user-images.githubusercontent.com/38302725/39341302-d3952d0c-4a15-11e8-926d-7f288882bbc5.png)

Please look into it.

**Comment by natt-tester** [comment]
The expired session is a good idea, but please look into this behavior:

![2018-05-08_18h08_58](https://user-images.githubusercontent.com/38302725/39745812-b99b7f80-52eb-11e8-970d-75db4b8937cb.gif)

**Comment by ldeveloperl1985** [comment]
link to https://github.com/GluuFederation/gluu-gateway/issues/94
