### ISSUE TITLE
Bug: Illogical validation in Admin Panel

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#83]
While creating an API in the Admin Panel, there's illogical information given to the user. The API name is described as optional, but it is required to actually create the API. Please refer to the screenshot.
![2018-04-29_19h30_15](https://user-images.githubusercontent.com/38302725/39405389-87ba05b4-4be7-11e8-990b-0ad73f959e8b.png)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, it's fixed:
![2018-05-07_16h27_48](https://user-images.githubusercontent.com/38302725/39687901-c06bf7be-5213-11e8-9b0b-59083af4d748.png)
