### ISSUE TITLE
Bug: illogical edition of an API

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#84]
Steps:
1. Click on APIS 
2. Click on ADD NEW API 
3. Fill in the Name, Host and Upstream URL 
4. Click on Submit API 
5. Click on the edition button with the same API 
6. Remove the Host 
7. Click Submit changes

Expected: The submission fails because "At least one of hosts, uris, or methods should be specified."
Actual: The submission succeeds, the API doesn't have any  hosts, uris, or methods should specified.

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, this validation bug is fixed. However, when you remove all the default values from the fields visible in the screenshot, and click SUBMIT CHANGES, you get a 500 error. Please check the validation of all the API creation/edition fields.
![2018-05-07_16h39_08](https://user-images.githubusercontent.com/38302725/39688599-d5691e50-5216-11e8-8f51-666d42c3107c.png)

**Comment by ldeveloperl1985** [comment]
Done and tested
