### ISSUE TITLE
Bug: bottom toggle bar of a different shape&size

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#85]
Please refer to the Admin Panel screenshots and fix the shape&size of the bottom toggle bar. It seems that the change only affects the bottom bar on each page.

![2018-04-29_19h26_10](https://user-images.githubusercontent.com/38302725/39405504-70b0cf4a-4be9-11e8-965d-0598b805d9ae.png)
![2018-04-29_20h02_49](https://user-images.githubusercontent.com/38302725/39405516-abe585ba-4be9-11e8-8187-f2c979a53e9d.png)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, it's fixed.

**Comment by natt-tester** [comment]
The weird toggle bars are back:
![2018-06-03_21h35_40](https://user-images.githubusercontent.com/38302725/40886448-56ffa62c-677b-11e8-8fa2-e390c00ae7ae.png)

**Comment by ldeveloperl1985** [comment]
Done
![weirdtogglebar](https://user-images.githubusercontent.com/2329776/40960656-0d5e0290-68be-11e8-9be8-fa04eee28b9a.png)
