### ISSUE TITLE
Bug: weird toggle bar

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#87]
Steps:

1. Log in to the Admin Panel
2. Click on CONSUMERS --> IMPORT
3. Click on CSV or Google Spreadsheet

Expected: The toggle bars of the dialog windows look ok, set to YES or NO by default.
Actual: The toggle bars of the dialog windows look weird, stuck between YES and NO.
![2018-04-30_07h43_44](https://user-images.githubusercontent.com/38302725/39411893-ec5a8b56-4c55-11e8-8dea-4d1fe78a8ef0.png)
![2018-04-30_07h44_16](https://user-images.githubusercontent.com/38302725/39411895-ef9fac06-4c55-11e8-8ae0-8948396b4d01.png)

**Comment by ldeveloperl1985** [comment]
Done
