### ISSUE TITLE
Bug: multiple clicks on buttons generate multiple dialog windows

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#88]
Please refer to the gif and fix this issue:

![2018-04-30_09h11_31](https://user-images.githubusercontent.com/38302725/39411943-db1bca0c-4c56-11e8-8c43-6f568736b395.gif)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Please refer to the video -- I believe it still needs some improvement. I have observed this behavior in several dialog windows immediately after the first login and every time I clear the cache.
![2018-05-08_11h35_56](https://user-images.githubusercontent.com/38302725/39733227-000527fa-52b5-11e8-9487-0bb5a01381a1.gif)

**Comment by ldeveloperl1985** [comment]
Done
