### ISSUE TITLE
Bug: wrong default value

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#89]
Please refer to the screenshot and fix the default value of the button to true.
![2018-04-30_22h34_38](https://user-images.githubusercontent.com/38302725/39429910-c0f950d0-4ccf-11e8-8c8d-7806a3b5b084.png)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, it's fixed by setting the default value to FALSE.
![2018-05-08_11h56_03](https://user-images.githubusercontent.com/38302725/39733589-d897cfae-52b6-11e8-920f-6a85c2a633c3.png)
