### ISSUE TITLE
Bug: Flawed Upstream view

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#90]
Please refer to the video and fix the bug that occurs when you try to view the details of an Upstream and/or add a Target.
![2018-05-02_20h12_43](https://user-images.githubusercontent.com/38302725/39518483-6ba5ee90-4e46-11e8-899e-938fe559737a.gif)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, this bug is fixed.
