### ISSUE TITLE
Bug: impossible import

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#95]
Steps:
1. Log in to the AP
2. Go to Snapshots and click IMPORT.
3. Choose any file and click open.

Expected: The file is imported OR there is a validation error for incorrect file types.
Actual: The console shows "Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html http://errors.angularjs.org/1.5.11/$sce/itype?p0=html"

![2018-05-08_12h44_39](https://user-images.githubusercontent.com/38302725/39735327-759253cc-52be-11e8-8e5f-9a7a118ec341.gif)

**Comment by ldeveloperl1985** [comment]
Done
