### ISSUE TITLE
Bug: duplication instead of Target deletion

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#96]
Precondition: a created Upstream with a Target

Steps:
1. Log in to the AP
2. Go to Upstreams and click on a created one --> DETAILS
3. Click on Targets
4. Click DELETE

Expected: The Target is deleted.
Actual: The Target is copied. You can create multiple identical Targets using this bug.

![2018-05-08_12h56_17](https://user-images.githubusercontent.com/38302725/39735982-708526a4-52c1-11e8-80cb-02a68e14fb22.gif)

**Comment by ldeveloperl1985** [comment]
This is aspected behavior for a target. Because the upstream maintains a history of target changes, the targets cannot be deleted or modified. 
For more description: https://getkong.org/docs/0.11.x/admin-api/#target-object
Agree?

**Comment by natt-tester** [comment]
Wow, then it's good it's not on our side. I understand maintaining a history of changes, but trying to delete a "deleted" object and thus producing an even longer list of "changes" seems a bit pointless to me;) No-bug, then!
