### ISSUE TITLE
Bug: extra dialog window

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#97]
It's not a blocker, but for better UX the SUBMIT API window should be removed. It always pops up first when you want to create a new API (please refer to the gif).

![2018-05-08_13h19_52](https://user-images.githubusercontent.com/38302725/39736401-1e5bb210-52c3-11e8-989e-87c3b228e5f3.gif)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
It's better, but the animation is a bit off:
-- the API window just appears in the middle of the screen and slides up when cancelled/done, not slides down to appear like the other dialog windows
-- the API window doesn't appear instantly, it can take a longer while to pop up. In the meantime, there is a trace of the removed window underneath:

![2018-05-11_12h01_37](https://user-images.githubusercontent.com/38302725/39902809-43547fbe-5513-11e8-9a51-287447a64846.png)
![Uploading 2018-05-11_11h56_33.gif…]()

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
Agreed, nicely fixed! :)
