### ISSUE TITLE
Bug (?): problematic Upstream edition

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#98]
Precondition: a created Upstream
STEPS:
1. Log in to the AP
2. Go to Upstreams and click on DETAILS of a chosen Upstream
3. Try to edit the Slots or the Orderlist.

Expected: You can edit the Slots or the Orderlist.
Actual: You get an error message even if the number of Slots is the same as the Orderlist.
![2018-05-08_16h33_01](https://user-images.githubusercontent.com/38302725/39741837-b2603146-52de-11e8-9f5b-04b15b06566d.gif)

**Comment by ldeveloperl1985** [comment]
I think you are doing wrong. See the description of `orderlist` field.

```
A list of sequential, but randomly ordered, integer numbers that determine the distribution of the slots in the balancer. If omitted it will be generated. If given, it must have exactly slots number of entries.
```

It must be sequential. If you delete any number randomly then it shows `invalid orderlist`.

Example: 
orderlist [2,3,8,1,6,4,5,7]. if you delete 3 then not allow because this is not in sequential. you can delete 8.
Agree?

**Comment by natt-tester** [comment]
Agreed, I have just tested it by deleting no. 1000, 999, 998, etc. and changing the Slots number accordingly. It works fine if you do it this way :)
