### ISSUE TITLE
Bug: enigmatic error message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#99]
Steps:
1. Log in to the AP
2. Click on CONNECTIONS
3. Click on NEW CONNECTION
4. Click on CREATE CONNECTION

Expected: The validation errors are understandable and informative.
Actual: There is an enigmatic message for the Kong Admin URL field. Please refer to the screenshot.

![2018-05-08_13h00_48](https://user-images.githubusercontent.com/38302725/39742346-7a423a6e-52e0-11e8-92cb-30bd540ada39.png)

**Comment by ldeveloperl1985** [comment]
Done
![connectionerro](https://user-images.githubusercontent.com/2329776/39810415-925a7c84-53a2-11e8-875a-c9752d3907c3.png)

**Comment by natt-tester** [comment]
Agreed, it's fixed.
